### ISSUE TITLE
application.yml file can't find nacos

### ISSUE THREAD

**Issue by heytong** [apache/skywalking#5162] opened 2020-07-23 09:42 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ * ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
-  Nacos is not supported in configuration files(version: 8.0.1)?

**Comment by kezhenxu94** [comment] 2020-07-23 09:48
Duplicate of #4937

**Closed by kezhenxu94** 2020-07-23 09:48 UTC
