### ISSUE TITLE
 org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker - 192 [pool-4-thread-1] ERROR [] - Can't split instance id into 2 parts, .1_org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_

### ISSUE THREAD

**Issue by goodjuan-xj** [apache/skywalking#6125] opened 2021-01-04 01:06 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS, and JRE?
 skywalking8.1.0,elasticsearch 6.4.0
- Which company or project?

- What happened?
 org.apache.skywalking.oap.server.core.analysis.worker.MetricsPersistentWorker - 192 [pool-4-thread-1] ERROR [] - Can't split instance id into 2 parts, .1_org.apache.skywalking.oap.server.core.UnexpectedException: Can't split instance id into 2 parts, .1_

**Comment by kezhenxu94** [comment] 2021-01-04 02:44
Duplicate of #5791

**Closed by kezhenxu94** 2021-01-04 02:44 UTC
