### ISSUE TITLE
SpringCloudGateway More than 300 spans required to create

### ISSUE THREAD

**Issue by DerekHQ** [apache/skywalking#3161] opened 2019-07-24 10:06 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking version: 6.2.0
OS: Redhat4 
jdk: jdk1.8
spring-boot 2.1.4-RELEASE
spring-cloud-dependencies: Greenwich.SR2
spring-cloud-starter-gateway: 2.1.2.RELEASE
spring-webflux: 5.1.6.RELEASE

- Which company or project?

- What happen?
It is a sample project, only two levels, just  gateway-> service for echo demo.
At first, it's work fine! 
But, when I using Apachebench(ab) to stress testing,  then agent throw exception:

-----------------agent log-----------------

_WARN 2019-07-24 17:40:14:099 reactor-http-epoll-10 TracingContext :  More than 300 spans required to create 
java.lang.RuntimeException: Shadow tracing context. Thread dump
        at org.apache.skywalking.apm.agent.core.context.TracingContext.isLimitMechanismWorking(TracingContext.java:543)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.access$100(TracingContext.java:46)
        at org.apache.skywalking.apm.agent.core.context.TracingContext$5.doProcess(TracingContext.java:322)
        at org.apache.skywalking.apm.agent.core.dictionary.PossibleFound.doInCondition(PossibleFound.java:50)
        at org.apache.skywalking.apm.agent.core.context.TracingContext.createExitSpan(TracingContext.java:318)
        at org.apache.skywalking.apm.agent.core.context.ContextManager.createExitSpan(ContextManager.java:122)
        at org.apache.skywalking.apm.plugin.spring.cloud.gateway.v2.HttpClientOperationsSendInterceptor.beforeMethod(HttpClientOperationsSendInterceptor.java:56)
        at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:82)
        at reactor.netty.http.client.HttpClientOperations.send(HttpClientOperations.java)
        at org.springframework.cloud.gateway.filter.NettyRoutingFilter.lambda$filter$2(NettyRoutingFilter.java:140)
        at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.requestWithBody(HttpClientConnect.java:569)
        at reactor.netty.http.client.HttpClientConnect$HttpObserver.lambda$onStateChange$0(HttpClientConnect.java:424)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
        at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:425)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:511)
        at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.run(PooledConnectionProvider.java:540)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at java.lang.Thread.run(Thread.java:748)_

**Comment by zhaoyuguang** [comment] 2019-07-24 10:13
I found that when the traffic is large, the thread will not enter the `HttpClientOperationsStatusInterceptor` method to exit the gateway.entrySpan, so the gateway segment cannot be finished, I also find the missing point again. If you find it, welcome to fix it.

**Comment by wu-sheng** [comment] 2019-07-24 10:15
If you have  found the cause, send a quick fix please. @zhaoyuguang

**Comment by zhaoyuguang** [comment] 2019-07-24 10:17
> If you have found the cause, send a quick fix please. @zhaoyuguang

no problem

**Comment by DerekHQ** [comment] 2019-07-24 10:45
Thanks!

**Comment by wu-sheng** [comment] 2019-08-16 00:42
@DerekHQ Check the master branch please, this should be fixed by @zhaoyuguang

**Closed by wu-sheng** 2019-08-16 00:42 UTC
Labels: agent, bug, plugin
