### ISSUE TITLE
This error does not know how to solve? Can anyone help me see？

### ISSUE THREAD

**Issue by liyuyun** [apache/skywalking#1295] opened 2018-05-31 03:16 UTC
![1222](https://user-images.githubusercontent.com/31084497/40759578-352afb9a-64c5-11e8-9183-7a9bab8b241e.png)

Exception in thread "main" java.util.ServiceConfigurationError: org.apache.skywalking.apm.collector.core.module.ModuleProvider: Provider org.apache.skywalking.apm.collector.ui.jetty.UIModuleJettyProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.skywalking.apm.collector.core.module.ModuleDefine.prepare(ModuleDefine.java:62)
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:53)
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45)
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 5 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

**Comment by wu-sheng** [comment] 2018-05-31 03:43
I am not familiar with Eclipse env. Also in IntelliJ. We already provided document about how to build our source codes in command line, and only provided that, because that stays unchangeable. 

https://github.com/apache/incubator-skywalking/blob/master/docs/en/How-to-build.md

**Comment by wu-sheng** [comment] 2018-05-31 03:44
And if you are not familiar with all SkyWalking project structure, I don't recommend you to start from run in IDE. We provide binary distribution, please consider to use that.

**Comment by peng-yongsheng** [comment] 2018-06-04 14:57
IntelliJ is so good, advise you give up eclipse.  ^_^
Is there anybody can help him for the eclipse issue?

**Comment by zone1511** [comment] 2018-06-24 15:40
his error's root cause is Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServlet
@liyuyun do you check if your maven dependency able to include the servlet dependency?

**Comment by wu-sheng** [comment] 2019-05-22 12:34
Closing. No update. And we still recommend using IntelliJ

**Closed by wu-sheng** 2019-05-22 12:34 UTC
Labels: help wanted
