### ISSUE TITLE
Hystrix plugin should not  throw exception out

### ISSUE THREAD

**Issue by dominicqi** [apache/skywalking#4053] opened 2019-12-13 03:05 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [+] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

https://github.com/apache/skywalking/blob/fd24a29b3b0451d6a8527beae1ac5d6ff97c8600/apm-sniffer/apm-sdk-plugin/hystrix-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/hystrix/v1/SWExecutionHookWrapper.java

The Hystrix plugin use `HystrixCommandExecutionHook` , i think  `SWExecutionHookWrapper` should catch Throwable , not thrown. if the plugin throw a exception , will make hystrix fast-fail with no fallback。 
This happend in my application. The hook throw a exception 'No active span',then hystrixCommand fail without fallback. I haven't found out why yet ,but i think the plugin should not thrown exception to the apllication .

**Comment by wu-sheng** [comment] 2019-12-13 03:28
Is this exception caused by plugin? I don’t see the throw in the plugin codes. Could you explain more?

**Comment by dominicqi** [comment] 2019-12-13 03:35
> Is this exception caused by plugin? I don’t see the throw in the plugin codes. Could you explain more?

The  exception throw in `ContextManager.capture()` -> `TracingContext.activeSpan()` . But i haven't found out the root cause.

**Comment by wu-sheng** [comment] 2019-12-13 03:39
Could you share the exception?

**Comment by dominicqi** [comment] 2019-12-13 03:44
I think the `HystrixCommandRunInterceptor`  will create a `LocalSpan` before .   So what I don't understand is why the exception thrown . I'll keep looking，but I don't think this exception should make  application error.
Here is the stack.
`java.lang.IllegalStateException: No active span. at org.apache.skywalking.apm.agent.core.context.TracingContext.activeSpan(TracingContext.java:392) at org.apache.skywalking.apm.agent.core.context.TracingContext.capture(TracingContext.java:195) at org.apache.skywalking.apm.agent.core.context.ContextManager.capture(ContextManager.java:146) at org.apache.skywalking.apm.plugin.hystrix.v1.SWExecutionHookWrapper.onStart(SWExecutionHookWrapper.java:182) at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2125) at com.netflix.hystrix.AbstractCommand$ExecutionHookDeprecationWrapper.onStart(AbstractCommand.java:2132) at com.netflix.hystrix.AbstractCommand.applyHystrixSemantics(AbstractCommand.java:520) at com.netflix.hystrix.AbstractCommand.access$200(AbstractCommand.java:60) at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:419) at com.netflix.hystrix.AbstractCommand$4.call(AbstractCommand.java:413) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) at rx.Observable.unsafeSubscribe(Observable.java:10211) at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) at rx.Observable.unsafeSubscribe(Observable.java:10211) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10211) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41) at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30) at rx.Observable.unsafeSubscribe(Observable.java:10211) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51) at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) at rx.Observable.subscribe(Observable.java:10307) at rx.Observable.subscribe(Observable.java:10274) at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:51) at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:412) at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:378) ... 118 common frames omitted`

**Comment by wu-sheng** [comment] 2019-12-13 06:30
Yes, this error should not propagate to the Application. We should find out why.

**Comment by dominicqi** [comment] 2019-12-16 07:10
I found that ,because  the application use redisson version not support。 Redisson plugin create `Context` but when `createSpan` failed. Then the hook find the ContextManager isActive ,but the activeSpanStack  is empty.

**Comment by wu-sheng** [comment] 2019-12-16 07:11
@dominicqi Could you help on the redisson part? So, this issue should be closed, right?

**Comment by dominicqi** [comment] 2019-12-16 07:45
@wu-sheng I don't think it is redisson plugin bug ? Because i use the redisson version the plugin not support。 This Issue could closed. But  i still think the error should not propagate to the Application. 
What do you mean in redisson part?

**Comment by wu-sheng** [comment] 2019-12-16 07:47
>  don't think it is redisson plugin bug ? Because i use the redisson version the plugin not support。 This Issue could closed. But i still think the error should not propagate to the Application.

You could submit a PR to fix this. Add a context#active check before the NPE happens?

> What do you mean in redisson part?

You could enhance the redisson plugin for more versions, especially they are new.

**Comment by wu-sheng** [comment] 2019-12-18 01:19
Closing for now. @dominicqi If you have interests about the NPE fix, please let me know

**Closed by wu-sheng** 2019-12-18 01:19 UTC
Labels: question
