### ISSUE TITLE
[OAP Server] k8s client configmap informer log too verbose

### ISSUE THREAD

**Issue by chanjarster** [apache/skywalking#8198] opened 2021-11-29 05:33 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

Version 8.8.1

K8S version: v1.20.11

Startup log:

```
...
2021-11-29 05:24:14,854 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 64 [main] INFO  [] - Get a module define from application.yml, module name: cluster 
2021-11-29 05:24:14,855 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 68 [main] INFO  [] - Get a provider define belong to cluster module, provider name: kubernetes 
2021-11-29 05:24:14,857 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 117 [main] INFO  [] - Provider=kubernetes config=namespace has been set as skywalking-test 
2021-11-29 05:24:14,857 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 117 [main] INFO  [] - Provider=kubernetes config=labelSelector has been set as app=skywalking-test,release=skywalking-test,component=oap 
2021-11-29 05:24:14,858 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 117 [main] INFO  [] - Provider=kubernetes config=uidEnvName has been set as SKYWALKING_COLLECTOR_UID 
...
2021-11-29 05:24:14,924 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 68 [main] INFO  [] - Get a provider define belong to configuration module, provider name: k8s-configmap 
2021-11-29 05:24:14,925 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 117 [main] INFO  [] - Provider=k8s-configmap config=period has been set as 60 
2021-11-29 05:24:14,925 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 117 [main] INFO  [] - Provider=k8s-configmap config=namespace has been set as skywalking-test 
2021-11-29 05:24:14,925 org.apache.skywalking.oap.server.starter.config.ApplicationConfigLoader 117 [main] INFO  [] - Provider=k8s-configmap config=labelSelector has been set as app=skywalking-test,release=skywalking-test,component=oap 
...
2021-11-29 05:24:17,875 org.apache.skywalking.oap.server.library.module.ModuleDefine 89 [main] INFO  [] - Prepare the k8s-configmap provider in configuration module. 
...
2021-11-29 05:24:18,248 org.apache.skywalking.oap.server.library.module.BootstrapFlow 46 [main] INFO  [] - start the provider k8s-configmap in configuration module. 

```

After startup several minutes, oap start print below logs repeatedly, frequently and endlessly:

```
2021-11-29 03:58:13,574 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,581 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,588 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,639 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,644 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,649 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,654 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,664 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,669 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,673 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,678 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,682 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,686 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,692 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,696 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,701 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,705 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,709 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,713 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,718 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,721 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,725 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,729 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,732 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,745 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,791 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,795 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,800 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,804 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,808 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,813 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,817 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,821 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,825 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,829 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,833 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,838 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,845 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,852 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,864 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,868 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,872 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,877 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,880 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,884 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,889 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,894 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,898 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,904 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,907 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,910 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,914 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,917 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,921 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,925 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,933 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,939 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,943 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,947 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,953 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,957 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,961 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,965 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,969 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,974 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,979 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,982 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,987 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,991 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,995 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:13,998 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,003 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,007 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,012 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,016 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,021 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,025 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,030 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,036 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,040 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,046 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,052 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,057 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,062 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,066 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,070 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,075 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 

```

### What you expected to happen

Not too much logging.

### How to reproduce

Using [helm chart](https://github.com/apache/skywalking-kubernetes/blob/v4.1.0/chart/skywalking/README.md).

Prepare `values.yaml`:

```yaml
ui: 
  image:
    tag: 8.8.1
  resources: 
    requests: 
      cpu: "100m"
      memory: "1Gi"
    limits: 
      cpu: "2000m"
      memory: "1Gi"
oap: 
  image:
    tag: 8.8.1
  storageType: elasticsearch
  dynamicConfigEnabled: true
  resources: 
    requests: 
      cpu: "1"
      memory: "3Gi"
    limits: 
      cpu: "2"
      memory: "3Gi"
```

And install:

```bash
helm install "sw-test" skywalking -n "sw-test" --values /path/to/values.yaml
```

Wait for about **8 min** after oap server start up, logs will show.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment] 2021-11-29 05:36
This is strange, I never saw this in showcase. @kezhenxu94 Do we have some enhancements already?

**Comment by wu-sheng** [comment] 2021-11-29 05:37
And this is not a bug, remving tag.

**Comment by wu-sheng** [comment] 2021-11-29 05:38
Info level logs should have been disabled in binary already.

**Comment by chanjarster** [comment] 2021-11-29 05:44
> Info level logs should have been disabled in binary already.

Refer to [this comment](https://github.com/kubernetes-client/java/issues/1606#issuecomment-802860928):

> re-establishing watch connection every ~5min is the expected behavior, but re-connecting too frequently will be another issue

I think the real problem is not log level, but something else.

**Comment by kezhenxu94** [comment] 2021-11-29 05:53
> 2021-11-29 03:58:13,998 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,003 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 
2021-11-29 03:58:14,007 io.kubernetes.client.informer.cache.ReflectorRunnable 235 [controller-reflector-io.kubernetes.client.openapi.models.V1ConfigMap-1] INFO  [] - Watch connection expired: too old resource version: 14959806 (14961119) 


👆this kind of logs should be already resolved by https://github.com/apache/skywalking/pull/8122 it's tagged in 8.9.0 OAP though

**Closed** 2021-11-29 05:55 UTC
Labels: backend

**Comment by kezhenxu94** [comment] 2021-11-29 06:01
As for the log level, it's rather easy to override the log level of any class or even the whole logger system via dynamic config or static config, just FYI if you are not already found, like this https://github.com/apache/skywalking-showcase/blob/9b9e6a7f661df67e9d0396afe972da2cff1bfe61/deploy/platform/kubernetes/feature-cluster/resources.yaml#L53-L63

**Comment by chanjarster** [comment] 2021-11-29 06:02
Thanks @kezhenxu94 , is there any chance to change logging level by system properties or environment variables?

**Comment by kezhenxu94** [comment] 2021-11-29 06:21
> Thanks @kezhenxu94 , is there any chance to change logging level by system properties or environment variables?

I’m not sure either. You can refer to the manual of log4j2 or slf4j

**Comment by chanjarster** [comment] 2021-11-29 06:25
OK, thank you again.
