### ISSUE TITLE
[Nodejs] Type check failed in typescript

### ISSUE THREAD

**Issue by woolson** [apache/skywalking#6195] opened 2021-01-13 06:11 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

### Bug
- Which version of SkyWalking, OS, and JRE?
`skywalking-backend-js@0.1.0`

- Which company or project?

- What happened?
If possible, provide a way to reproduce the error. e.g. demo application, component version.

**Error** Module '"../../proto/language-agent/Tracing_pb"' has no exported member 'SpanLayer'.
reproduce steps:
1.  Install ``skywalking-backend-js@0.1.0` in typescript project
2. Error message `Module '"../../proto/language-agent/Tracing_pb"' has no exported member 'SpanLayer'.` will happen there.
3. Because of some .d.ts file in `src/proto/` content is missed after build(you can check folder `lib/proto/*.d.ts`).

**Comment by kezhenxu94** [comment] 2021-01-13 09:01
Duplicate of #6129

**Comment by kezhenxu94** [comment] 2021-01-13 09:02
This is a known issue #6129 , I'm closing this issue, let's track this bug there #6129

**Closed by kezhenxu94** 2021-01-13 09:01 UTC

**Comment by woolson** [comment] 2021-01-14 09:11
ok
