### ISSUE TITLE
OAP server's performance issue

### ISSUE THREAD

**Issue by yantaowu** [apache/skywalking#3224] opened 2019-08-07 03:36 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ✔️] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
6.0.0-GA，centOS，jdk1.8
- Which company or project?
Tongcheng（同程金服）

- What happen?
Skywalking UI will not obtain trace data after the OAP server runs 
for a period of time and ES does't have data also. But reboot 
the OAP server, SW UI can obatin the data. I dump the thread when the OAP 
server does't work. After I analysis the dump file, 
I find the GRPC's thread that put the trace data into buffer is in 
sleeping state and the persistence worker which consume the buffer also blocked.

___
### Requirement or improvement
I think the root cause is the visibility issue in multithread programming. According to JMM(Java Memory Model),  when one thread modify the buffer, the other thread can't obtain the modified result immediately without any synchronized measure. So I change the buffer array to the JDK ArrayBlockingQueue, use blocking queue to guarantee the visibility between the different threads.
       In the code I use none blocking method，if you want to use blocking way，you should change the offer method to put method.
![1](https://user-images.githubusercontent.com/28336000/62592889-690ed480-b907-11e9-9016-a18977cd9063.png)

**Comment by wu-sheng** [comment] 2019-08-07 07:00
For your queue question, I don't it is multiple threads visible issue. You are using 6.0.0-GA, back to there, OAP created several threads(including queue) to deal with one kind of metrics, such as service_p99, service_p95. But actually, we don't need that much, in 6.1.0 -> 6.3.0(release soon), we have optimized the thread model very much, we have a new shared consumer thread pool to avoid the root cause, which is also the root cause of your scenario, that is too many unnecessary threads, triggering high CPU load.

You could dig a little more about the master branch, to see what we are doing today. From the thread dump we get from the latest version, consumer threads are still more than necessary, but we wouldn't keep to too low to support very high payload/throughput in OAP.

**Comment by wu-sheng** [comment] 2019-08-18 00:06
@yanfch Any update? 6.4.0 milestone is set to release in next month by default. If you have anything to discuss and improve, I think we should start it now.

**Comment by wu-sheng** [comment] 2019-08-27 07:33
Closing this because of no further update.

**Closed by wu-sheng** 2019-08-27 07:33 UTC
Labels: No Update, question
