### ISSUE TITLE
get error from oap

### ISSUE THREAD

**Issue by csz711** [apache/skywalking#7095] opened 2021-06-10 07:14 UTC
1、info about es and skywaling
**es version**:elasticsearch-oss:6.7
**skywalking:**
```
helm install skywalking skywalking -n istio-system \ 
  --set oap.env.SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS=k8s-mesh \
  --set oap.envoy.als.enabled=true \
  --set ui.image.tag=8.1.0 \
  --set oap.image.tag=8.1.0-es6 \
  --set oap.storageType=elasticsearch \
  --set elasticsearch.enabled=false \
  --set elasticsearch.config.host=elasticsearch-logging-data.kubesphere-logging-system \
  --set elasticsearch.config.port.http=9200
```
2、get error from oap
```
2021-06-10 06:25:53,868 - org.elasticsearch.client.RestClient -7448 [I/O dispatcher 1] WARN  [] - request [HEAD http://elasticsearch-logging-data.kubesphere-logging-system:9200/_template/instance_jvm_thread_peak_count] returned 1 warnings: [299 Elasticsearch-6.7.0-8453f77 "[types removal] The parameter include_type_name should be explicitly specified in get template requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."]
2021-06-10 06:25:53,870 - org.elasticsearch.client.RestClient -7450 [I/O dispatcher 1] WARN  [] - request [HEAD http://elasticsearch-logging-data.kubesphere-logging-system:9200/instance_jvm_thread_peak_count-20210610?ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true] returned 1 warnings: [299 Elasticsearch-6.7.0-8453f77 "[types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."]
2021-06-10 06:25:53,870 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager -7450 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.source.oal.rt.dispatcher.ServiceInstanceJVMMemoryDispatcher is added into DefaultScopeDefine 9.
2021-06-10 06:25:53,870 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager -7450 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.source.oal.rt.dispatcher.ServiceInstanceJVMGCDispatcher is added into DefaultScopeDefine 11.
2021-06-10 06:25:53,870 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager -7450 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.source.oal.rt.dispatcher.ServiceInstanceJVMThreadDispatcher is added into DefaultScopeDefine 33.
2021-06-10 06:25:53,870 - org.apache.skywalking.oap.server.core.analysis.DispatcherManager -7450 [main] INFO  [] - Dispatcher org.apache.skywalking.oap.server.core.source.oal.rt.dispatcher.ServiceInstanceJVMCPUDispatcher is added into DefaultScopeDefine 8.
2021-06-10 06:25:53,872 - org.apache.skywalking.oap.server.library.server.grpc.GRPCServer -7452 [main] INFO  [] - Bind handler JVMMetricReportServiceHandler into gRPC server 0.0.0.0:11800
2021-06-10 06:25:54,038 - org.apache.skywalking.oap.server.library.server.jetty.JettyServer -7618 [main] INFO  [] - start server, host: 0.0.0.0, port: 12800
2021-06-10 06:25:54,042 - org.eclipse.jetty.server.Server -7622 [main] INFO  [] - jetty-9.4.28.v20200408; built: 2020-04-08T17:49:39.557Z; git: ab228fde9e55e9164c738d7fa121f8ac5acd51c9; jvm 1.8.0_212-b04
2021-06-10 06:25:54,081 - org.eclipse.jetty.server.handler.ContextHandler -7661 [main] INFO  [] - Started o.e.j.s.ServletContextHandler@66a472b9{/,null,AVAILABLE}
2021-06-10 06:25:54,091 - org.eclipse.jetty.server.AbstractConnector -7671 [main] INFO  [] - Started ServerConnector@7b2a3ff8{HTTP/1.1, (http/1.1)}{0.0.0.0:12800}
2021-06-10 06:25:54,091 - org.eclipse.jetty.server.Server -7671 [main] INFO  [] - Started @7730ms
2021-06-10 06:25:54,093 - org.apache.skywalking.oap.server.core.storage.PersistenceTimer -7673 [main] INFO  [] - persistence timer start
2021-06-10 06:25:54,097 - org.apache.skywalking.oap.server.core.cache.CacheUpdateTimer -7677 [main] INFO  [] - Cache updateServiceInventory timer start
2021-06-10 06:26:08,551 - org.apache.skywalking.oap.server.receiver.envoy.als.Fetcher -22131 [load-pod-0] ERROR [] - code:0 header:null body:null
2021-06-10 06:26:08,552 - org.apache.skywalking.oap.server.receiver.envoy.als.Fetcher -22132 [load-pod-0] ERROR [] - code:0 header:null body:null
2021-06-10 06:26:08,553 - org.apache.skywalking.oap.server.receiver.envoy.als.Fetcher -22133 [load-pod-0] ERROR [] - code:0 header:null body:null
2021-06-10 06:26:08,553 - org.apache.skywalking.oap.server.receiver.envoy.als.Fetcher -22133 [load-pod-0] ERROR [] - code:0 header:null body:null
2021-06-10 06:26:08,554 - org.apache.skywalking.oap.server.receiver.envoy.als.Fetcher -22134 [load-pod-0] ERROR [] - code:0 header:null body:null
2021-06-10 06:26:08,555 - org.apache.skywalking.oap.server.receiver.envoy.als.Fetcher -22135 [load-pod-0] ERROR [] - code:0 header:null body:null
```

**Comment by kezhenxu94** [comment] 2021-06-10 07:28
Duplicate of https://github.com/apache/skywalking/issues/6513

**Closed by kezhenxu94** 2021-06-10 07:28 UTC
