### ISSUE TITLE
Can alarm rule be dynamically modified?

### ISSUE THREAD

**Issue by zhousiliang163** [apache/skywalking#2843] opened 2019-06-10 03:45 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Can alarm rule be dynamically modified?

**Comment by wu-sheng** [comment] 2019-06-10 05:54
Today, we don't support this. But you could send a pull request by following 
**15. Dynamic Configuration. Make configuration of OAP changed dynamic, from remote service or 3rd party configuration management system.** in [OAP setup document](https://github.com/apache/skywalking/blob/master/docs/en/setup/backend/backend-setup.md#advanced-feature-document-link-list)

I think this feature should be a good one.

**Comment by kezhenxu94** [comment] 2019-09-12 04:43
Duplicate of #3467

**Closed by kezhenxu94** 2019-09-12 04:43 UTC
Labels: OAP-backend, help wanted, plugin
