### ISSUE TITLE
intercept failure  org.apache.skywalking.apm.plugin.spring.mvc.commons.exception.IllegalMethodStackDepthException

### ISSUE THREAD

**Issue by appregidc** [apache/skywalking#2659] opened 2019-05-14 03:02 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking6.1GA centos
- Which company or project?
springboot +spring cloudt
- What happen?

from skywalkinglogs, it promt to submit bug
[new 2.txt](https://github.com/apache/skywalking/files/3175653/new.2.txt)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2019-05-14 03:21
Could you provide Spring version and your demo codes? We need to reproduce the issue.

**Comment by appregidc** [comment] 2019-05-14 05:47
only found one in exception log

**Comment by wu-sheng** [comment] 2019-05-14 06:04
We need codes, because others are using these, and no issue reported. We have test cases, but passed. So, we need you to provide detail, which could tell us how this error happens.

**Comment by appregidc** [comment] 2019-05-14 06:17
![image](https://user-images.githubusercontent.com/16357470/57674823-dede0980-7652-11e9-8ecb-47b37d837e30.png)

这个代码片段是否有帮助，，从异常中就找到这个地方？或者是否可以我们准备一下环境，您remote调试

**Comment by IanCao** [comment] 2019-05-16 02:43
> ![image](https://user-images.githubusercontent.com/16357470/57674823-dede0980-7652-11e9-8ecb-47b37d837e30.png)
> 
> 这个代码片段是否有帮助？从异常中就找到这个地方。或者是否可以我们准备一下环境，您remote调试

English only
could u provide a demo project that can run directly?

**Comment by SummerOfServenteen** [comment] 2019-06-26 07:27
@wu-sheng  ,i also encountered the same exception, but the exception message was different from that of him.
This log is printed too often. I have use sw in 7 applications,but the curious thing about it was that it was only happened in one application.Nevertheless, it does not affect data reporting.The exception was caused by which the value of enhancedClassField_ws was null.
![image](https://user-images.githubusercontent.com/31895647/60158610-0adcd500-9824-11e9-9e05-31498e9ff262.png)
This is the exception message.
[exception.txt](https://github.com/apache/skywalking/files/3328772/exception.txt)

I can't find the root cause,the only temporary solution I can think of is to catch this exception.

**Comment by SummerOfServenteen** [comment] 2019-06-26 07:31
The code is simple
![image](https://user-images.githubusercontent.com/31895647/60160180-62307480-9827-11e9-8e5f-fa9f2b279adc.png)

**Comment by wu-sheng** [comment] 2019-06-27 09:20
@ascrutae Why `pathMappingCache` is NULL? Some methods aren't being intercepted?

**Comment by IanCao** [comment] 2019-06-28 02:22
> RELEASE

could u provider this all code

**Comment by IanCao** [comment] 2019-06-28 02:23
> springVersion='4.1.6.RELEASE',the code is simple
> ![image](https://user-images.githubusercontent.com/31895647/60160180-62307480-9827-11e9-8e5f-fa9f2b279adc.png)

could u provide this all code

**Comment by SummerOfServenteen** [comment] 2019-06-28 06:35
I'm afraid I can't.

**Comment by wu-sheng** [comment] 2019-07-02 15:02
@SummerOfServenteen This makes things hard to locate and fix. I will make this open for one month Max. Look forward you could provide feedback and PR to fix.

**Comment by SummerOfServenteen** [comment] 2019-07-03 06:02
ok

**Comment by wu-sheng** [comment] 2019-07-20 08:59
Closing this due to no update. Please open a new one, if you find anything new.

**Closed by wu-sheng** 2019-07-20 08:59 UTC
Labels: TBD, agent, bug, plugin
