### ISSUE TITLE
Refresh the trace page and report an error

### ISSUE THREAD

**Issue by craneding** [apache/skywalking#7598] opened 2021-08-29 02:31 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Bug
- Which version of SkyWalking, OS and JRE?
   version: docker image apache/skywalking-oap-server:8.7.0-es7 and apache/skywalking-ui:8.7.0
   OS: CentOS Linux release 7.9.2009 (Core)
   JRE: 11

- What happened?
   Refresh the trace page and report an error, Refresh the topology page、profile page、log page、alarm page、event page also reports an error.

Before manually refreshing the page:
![image](https://user-images.githubusercontent.com/6929198/131236199-7db64cde-e430-485d-a13a-41f222bbccbf.png)

After manually refreshing the page:
![image](https://user-images.githubusercontent.com/6929198/131236203-2a184691-9c06-44e7-a7c5-f98f675f55a8.png)

**Comment by kezhenxu94** [comment] 2021-08-29 03:28
Please search before opening an issue

**Comment by kezhenxu94** [comment] 2021-08-29 03:28
Duplicate of #7397

**Closed by kezhenxu94** 2021-08-29 03:28 UTC
