### ISSUE TITLE
use elasticsearch7.3.2 RestHighLevelClient ERROR

### ISSUE THREAD

**Issue by richard403** [apache/skywalking#4776] opened 2020-05-12 03:32 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Bug
__
### Bug
- Which version of SkyWalking, OS and JRE?
skywalking-7.0.0-es7, centos, java8

- Which company or project?
app which use elasticsearch7.3.2 RestHighLevelClient

- What happen?
error
```
[ERROR]-[2020-05-12 10:52:54,201]-[es_rest_client_sniffer[T#1]]-[org.elasticsearch.client.sniff.Sniffer]-[org.elasticsearch.client.sniff.Sniffer$Task.run(Sniffer.java:141)]:error while sniffing nodes
java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:796) ~[elasticsearch-rest-client-7.3.2.jar!/:7.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218) ~[elasticsearch-rest-client-7.3.2.jar!/:7.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205) ~[elasticsearch-rest-client-7.3.2.jar!/:7.3.2]
	at org.elasticsearch.client.sniff.ElasticsearchNodesSniffer.sniff(ElasticsearchNodesSniffer.java:104) ~[elasticsearch-rest-client-sniffer-7.3.2.jar!/:7.3.2]
	at org.elasticsearch.client.sniff.Sniffer.sniff(Sniffer.java:209) ~[elasticsearch-rest-client-sniffer-7.3.2.jar!/:7.3.2]
	at org.elasticsearch.client.sniff.Sniffer$Task.run(Sniffer.java:139) ~[elasticsearch-rest-client-sniffer-7.3.2.jar!/:7.3.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.11.jar!/:4.4.11]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute$original$QBOPJDUz(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute$original$QBOPJDUz$accessor$mF0toxew(InternalHttpAsyncClient.java) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient$auxiliary$t1jzrKVV.call(Unknown Source) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:85) ~[skywalking-agent.jar:7.0.0]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:214) ~[elasticsearch-rest-client-7.3.2.jar!/:7.3.2]
	... 11 more
```
```
ava.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:796)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1454)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1424)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1394)
	at org.elasticsearch.client.RestHighLevelClient.search$original$uJCoUnLo(RestHighLevelClient.java:930)
	at org.elasticsearch.client.RestHighLevelClient.search$original$uJCoUnLo$accessor$FTlbRVWQ(RestHighLevelClient.java)
	at org.elasticsearch.client.RestHighLevelClient$auxiliary$1T6sQbUU.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java)
	at com.whx.job.dao.es.business.MaterialImgESDao.searchVectorByES(MaterialImgESDao.java:392)
	at com.whx.job.dao.es.business.MaterialImgESDao$$FastClassBySpringCGLIB$$df5b2fac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.whx.job.dao.es.business.MaterialImgESDao$$EnhancerBySpringCGLIB$$52d8e838.searchVectorByES(<generated>)
	at com.whx.job.imgcnn.base.ImgSimilarOpt.imgCnnSimilar(ImgSimilarOpt.java:186)
	at com.whx.job.imgcnn.service.ImgCnnService.searchImgSimilar(ImgCnnService.java:316)
	at com.whx.job.imgcnn.service.ImgCnnService.commitImgAudit(ImgCnnService.java:247)
	at com.whx.job.cron.MaterialSimilarThread.lambda$checkAuditMaterials$0(MaterialSimilarThread.java:111)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.whx.job.cron.MaterialSimilarThread.checkAuditMaterials(MaterialSimilarThread.java:105)
	at com.whx.job.cron.MaterialSimilarThread$$FastClassBySpringCGLIB$$65511108.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute$original$27OjV9uX(InternalHttpAsyncClient.java:123)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute$original$27OjV9uX$accessor$lJB3rLUq(InternalHttpAsyncClient.java)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient$auxiliary$pgFEcd8k.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInterWithOverrideArgs.intercept(InstMethodsInterWithOverrideArgs.java:85)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:214)
```

```
public void createEsClient() throws UnknownHostException {
        RestClientBuilder restClientBuilder = creatRestClientBuilder(getHttpHosts(esCluster));

        SniffOnFailureListener sniffOnFailureListener = new SniffOnFailureListener();
        restClientBuilder.setFailureListener(sniffOnFailureListener);
        restHighLevelClient = new RestHighLevelClient(restClientBuilder);

        sniffer = Sniffer.builder(restHighLevelClient.getLowLevelClient()).
                setSniffIntervalMillis(snifferinterval).setSniffAfterFailureDelayMillis(failuredelay).build();

        sniffOnFailureListener.setSniffer(sniffer);
        logger.info("create es host={}, user={}, client={}", esCluster, user, restHighLevelClient);
    }

// MaterialImgESDao.java:392
SearchResponse searchResponse = esConfigBase.getEsClient().search(searchRequest, RequestOptions.DEFAULT);
```

**Comment by wu-sheng** [comment] 2020-05-12 05:14
Check the test folder there is es plugin test. Please check the difference.

**Comment by wu-sheng** [comment] 2020-05-12 05:15
But to be honest, this Seems IO error, which is hardly caused by agent.

**Comment by wu-sheng** [comment] 2020-05-13 02:47
@aderm Could you take a look what is happenning?

**Comment by aderm** [comment] 2020-05-13 03:03
Ok, let me take a look

**Comment by aderm** [comment] 2020-05-13 03:12
@richard403 Could you provide us more query scenario about this error? It is better to have more detailed es query codes or parameters.

**Comment by aderm** [comment] 2020-05-13 03:18
Is this error reported by ES at the time of sniff? Or you can close sniff and try.

**Comment by aderm** [comment] 2020-05-21 05:00
Regarding the above abnormal information, the local test is started and called normally, and the above-mentioned error will appear during the APP application closing process.
![image](https://user-images.githubusercontent.com/2892433/82524458-901a5800-9b61-11ea-9771-de155ec27ef8.png)

At the same time, it is also tested that when the SW plugin interception is not added, the startup and call are normal, and the following exception will also occur during the APP closing process.
![image](https://user-images.githubusercontent.com/2892433/82524506-b8a25200-9b61-11ea-9d37-7422f13c7f47.png)

Based on the above analysis, it is preliminarily judged that the shutdown abnormality has nothing to do with the SK interception plugin. It may be related to the timing sniff detection mechanism of the ES itself, which will continue to be executed when the application is closed. Maybe you can try this direction.

**Comment by lanlin** [comment] 2020-05-27 08:05
### elasticsearch v7.6.2 got this error java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping

```shell
2020-05-27 15:45:54,532 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -7915 [main] ERROR [] - org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/h    ttp/Header;)Z
150 java.lang.NoSuchMethodError: org.elasticsearch.client.RestHighLevelClient.ping([Lorg/apache/http/Header;)Z
151     at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.connect(ElasticSearchClient.java:134) ~[library-client-7.0.0.jar:7.0.0]
152     at org.apache.skywalking.oap.server.storage.plugin.elasticsearch.StorageModuleElasticsearchProvider.start(StorageModuleElasticsearchProvider.java:212) ~[storage-elasticse    arch-plugin-7.0.0.jar:7.0.0]
153     at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-7.0.0.jar:7.0.0]
154     at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-7.0.0.jar:7.0.0]
155     at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
156     at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
```
https://discuss.elastic.co/t/nosuchmethoderror-for-org-elasticsearch-action-support-indicesoptions-ignorethrottled/195440/3

https://stackoverflow.com/questions/53610891/elasticsearch-java-client-initialization-fails

**Comment by wu-sheng** [comment] 2020-05-27 08:10
@lanlin You are asking at the wrong place. Your post is the backend error log, no related to this issue in any case.

**Comment by wu-sheng** [comment] 2020-05-27 08:10
Close as no update in 6 days.

**Closed by wu-sheng** 2020-05-27 08:10 UTC
Labels: TBD, agent, plugin

**Comment by lanlin** [comment] 2020-05-27 08:21
@wu-sheng sorry, I had set a wrong environment the `SW_STORAGE` should be `elasticsearch7` not `elasticsearch`

**Comment by goddenco** [comment] 2022-03-08 05:57
I upgraded the agent from 8.1.1 to 8.8.0 and reported an error：“Request cannot be executed; I/O reactor status:”
Then after restoring, no error is reported
