### ISSUE TITLE
监控对HttpURLConnection的支持

### ISSUE THREAD

**Issue by xiongshiyan** [apache/skywalking#2767] opened 2019-05-28 02:53 UTC
目前监控对客户端Http的支持如下，HTTPURLConnection还用的比较多，能提供支持吗？

Feign 9.x
Netflix Spring Cloud Feign 1.1.x, 1.2.x, 1.3.x
Okhttp 3.x
Apache httpcomponent HttpClient 4.2, 4.3
Spring RestTemplete 4.x
Jetty Client 9
Apache httpcomponent AsyncClient 4.x

**Comment by wu-sheng** [comment] 2019-05-28 02:54
English Only. And we are welcome contributions. We don't do all plugin by ourselves.

**Comment by kezhenxu94** [comment] 2019-05-28 02:55
Duplicate of #2709

**Closed by wu-sheng** 2019-05-28 02:54 UTC
