### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by it-ll** [apache/skywalking#8901] opened 2022-04-18 09:57 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

UI (apache/skywalking-booster-ui)

### What happened

mac上安装部署skywalking报错如下：
java.lang.NoClassDefFoundError: org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/InstanceMethodsAroundInterceptor
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_321]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_321]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_321]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_321]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_321]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_321]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_321]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_321]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_321]
        at com.google.common.reflect.ClassPath$ClassInfo.load(ClassPath.java:379) ~[guava-31.1-jre.jar:?]
        at org.apache.skywalking.oap.server.core.annotation.AnnotationScan.scan(AnnotationScan.java:57) ~[server-core-9.0.0.jar:9.0.0]
        at org.apache.skywalking.oap.server.core.CoreModuleProvider.prepare(CoreModuleProvider.java:179) ~[server-core-9.0.0.jar:9.0.0]
        at org.apache.skywalking.oap.server.library.module.ModuleDefine.prepare(ModuleDefine.java:96) ~[library-module-9.0.0.jar:9.0.0]
        at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:46) ~[library-module-9.0.0.jar:9.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:44) [server-starter-9.0.0.jar:9.0.0]
        at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:23) [server-starter-9.0.0.jar:9.0.0]
Caused by: java.lang.ClassNotFoundException: org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstanceMethodsAroundInterceptor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_321]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_321]
        ... 19 more

但可以正常访问，在ui页面中新建仪表盘时，缺少层选项，导入仪表盘也失败，页面一直转无响应

### What you expected to happen

正常新建仪表盘

### How to reproduce

mac部署，本地应用接入sky，访问页面，新建仪表盘

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by it-ll** [comment] 2022-04-18 09:58
应该是个bug吧，要不就是我安装部署有问题，版本为9.0.0

**Comment by wu-sheng** [comment] 2022-04-18 10:00
All issues and discussions must be in English. Closing.

**Closed** 2022-04-18 09:59 UTC
Labels: bug

**Comment by wu-sheng** [comment] 2022-04-18 10:01
`NoClassDefFoundError` usually is caused by your local deployment. Or special class loader. You have to check on your own.
