### ISSUE TITLE
[Feature] About support multi threads and auto finalize for skywalking-rust.

### ISSUE THREAD

**Issue by jmjoy** [apache/skywalking#9297] opened 2022-07-01 09:54 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Now the [`skywalking-rust`](https://github.com/apache/skywalking-rust) only support one thread tracing, but usually there are some scenes that require multi threads/coroutines tracing.

### Use case

Rust application requires multi threads and coroutines tracing.

### Related issues

<https://github.com/apache/skywalking-rust/pull/20#issuecomment-1153411401>
<https://github.com/apache/skywalking-rust/pull/26>
<https://github.com/apache/skywalking-rust/pull/28>

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jmjoy** [comment] 2022-07-01 09:55
I think the new api design is (fake code):

```rust
use skywalking_rust::context::trace_context::TracingContext;
use skywalking_rust::reporter::grpc::Reporter;
use tokio;

static TRACING_MANAGER: Lazy<TracingManager> = Lazy::new(|| TracingManager::default("svc", "ins"));

async fn handle_request(reporter: ContextReporter) {
    let mut ctx = TRACING_MANAGER.create_context();

    {
        // Generate an Entry Span when a request
        // is received. An Entry Span is generated only once per context.
        let span = ctx.create_entry_span("operation1").unwrap();

        // Something...

        {
            // Generates an Exit Span when executing an RPC.
            let span2 = ctx.create_exit_span("operation2").unwrap();
            
            // Something...

            // Drop span2 and finalize to ctx.
        }

        // Drop span and finalize to ctx.
    }

    // Create coroutine to handle async task.
    spawn(async move {
        let mut ctx2 = TRACING_MANAGER.create_context();

        {
            let span3 = ctx2.create_entry_span("operation3").unwrap();

            // Something...

            // Drop span2 and finalize to ctx2.
        }

        // Drop ctx2 and send to TRACING_MANAGER.
    });

    // Drop ctx and send to TRACING_MANAGER.
}

#[tokio::main]
async fn main() {
    let tx = Reporter::start("http://0.0.0.0:11800").await;

    // Start server...

    // Block to report.
    loop {
        let context = TRACING_MANAGER.receive_context();
        reporter.send(context).await;
    }
}
```

Add the `TracingManager` which should be singleton in the application, to manage the contexts, and use notify mechanism for reporting.

**Comment by wu-sheng** [comment] 2022-07-01 09:58
Do you want to implement `ctx#capture` and `ctx2#continous` in these APIs, which could link ctx and ctx in a whole trace although they are created in two threads originally?

**Comment by jmjoy** [comment] 2022-07-01 10:07
> Do you want to implement `ctx#capture` and `ctx2#continous` in these APIs, which could link ctx and ctx in a whole trace although they are created in two threads originally?

OK, let me think about the design of API.

**Comment by jmjoy** [comment] 2022-07-01 11:46
What is the purpose of `ctx#capture` and `ctx2#continous`? Is there other language can be referenced? I just think it can add a parameter like `TRACING_MANAGER.create_context(parent_context)`.

**Comment by lujiajing1126** [comment] 2022-07-01 12:25
> What is the purpose of `ctx#capture` and `ctx2#continous`? Is there other language can be referenced? I just think it can add a parameter like `TRACING_MANAGER.create_context(parent_context)`.

Every `Segment` in SkyWalking exists in a single thread while a transaction/trace may consist of multiple operations across threads. To rebuild the whole trace in the backend (i.e. OAP), we have to link segments together with the help of contextual information, e.g. `traceID`, `segmentID`, `spanID`.

`Context.capture` and `Context. continous` are key methods to **capture** the context in a thread and **restore** the "context" in another thread.

You may refer to java impl, https://github.com/apache/skywalking-java/blob/main/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ContextManager.java#L157

**Comment by jmjoy** [comment] 2022-07-03 07:35
I'm studying `capture` and `continous` through Java Kafka. I've opened `foo` and `bar` consumers, and produced messages through the request of `/mq2`.
![image](https://user-images.githubusercontent.com/8677974/177029906-6e35055e-6592-4450-8c0e-bcb7a9d2c443.png)


I've determined through breakpoint debugging that the application has called to generate `LocalSpan` of `Kafka/Producer/Callback`.
![image](https://user-images.githubusercontent.com/8677974/177029937-8f40a29c-eb38-4ef5-8da0-b6a55b8ca4ed.png)

But I'm confused that `LocalSpan` of `Kafka/Producer/Callback` is not displayed on the interface.

![image](https://user-images.githubusercontent.com/8677974/177029974-c93c2798-13c4-48dd-a6e6-6ecdf1db0daa.png)

**Comment by wu-sheng** [comment] 2022-07-03 08:00
Maybe some visualization bug? I am not sure about this.
Because this span has two references, one is RPC peer, the other is from the local span's snapshot. 

If you purely want to check capture and continuous, all async HTTP call or callback should include this case.

**Comment by jmjoy** [comment] 2022-07-03 09:20
> Maybe some visualization bug? I am not sure about this. Because this span has two references, one is RPC peer, the other is from the local span's snapshot.
> 
> If you purely want to check capture and continuous, all async HTTP call or callback should include this case.

Yes, I switch to using the old 8.x UI, and the `Kafka/Producer/Callback` is shown.

**Comment by wu-sheng** [comment] 2022-07-03 10:20
FYI @Fine0830 We may miss mutiple references in the span page in 9.x

**Comment by lujiajing1126** [comment] 2022-07-03 10:46
> Maybe some visualization bug? I am not sure about this. Because this span has two references, one is RPC peer, the other is from the local span's snapshot.
> 
> If you purely want to check capture and continuous, all async HTTP call or callback should include this case.

I've confirmed the issue with both 9.0.0 and 9.1.0.

The issue is caused by `EndpointDepFromCrossThreadAnalysisListener` introduced in v9, NPE is thrown during the analysis , then the segment will not be saved to the storage.

```
org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler - 75 [grpcServerPool-1-thread-14] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.core.source.EndpointRelation.prepare(EndpointRelation.java:101) ~[server-core-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.core.analysis.DispatcherManager.forward(DispatcherManager.java:59) ~[server-core-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.core.source.SourceReceiverImpl.receive(SourceReceiverImpl.java:36) ~[server-core-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener.lambda$build$0(EndpointDepFromCrossThreadAnalysisListener.java:130) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_332]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener.build(EndpointDepFromCrossThreadAnalysisListener.java:124) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_332]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.notifyListenerToBuild(TraceAnalyzer.java:75) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.doAnalysis(TraceAnalyzer.java:71) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.SegmentParserServiceImpl.send(SegmentParserServiceImpl.java:40) ~[agent-analyzer-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:72) [skywalking-trace-receiver-plugin-9.1.0.jar:9.1.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:63) [skywalking-trace-receiver-plugin-9.1.0.jar:9.1.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [grpc-stub-1.46.0.jar:1.46.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.46.0.jar:1.46.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.46.0.jar:1.46.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
```

**Comment by wu-sheng** [comment] 2022-07-03 11:27
@lujiajing1126 Could you be more specific what causes the NPE?

**Comment by lujiajing1126** [comment] 2022-07-03 14:56
> @lujiajing1126 Could you be more specific what causes the NPE?

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/2568208/177045171-110b90ce-43bf-4878-b022-783dbf038b0a.png">

Since `sourceEndpointOwnerServiceName` is not null ("kafka-scenario"), but `sourceEndpointOwnerServiceLayer` is null.

Then, `serviceLayer.isNormal()` will report NPE,

<img width="985" alt="image" src="https://user-images.githubusercontent.com/2568208/177045223-aabd7e0b-8ead-40bf-b282-dc17c7e3269e.png">

I suppose, we miss a line here,

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/2568208/177045352-ab02b257-bd96-4fdf-a563-8e78ef1c903f.png">

We have to add `sourceBuilder.setSourceEndpointOwnerServiceLayer(Layer.GENERAL);` after line 95 just as we have done in the `RPCAnalysisListener.java`

**Comment by wu-sheng** [comment] 2022-07-03 15:26
Could you send a pull request to fix this?

**Comment by wu-sheng** [comment] 2022-07-03 15:29
I think this should be set to the owner layer, according to `sourceEndpointOwnerServiceName == null`, right?

**Comment by lujiajing1126** [comment] 2022-07-04 01:29
> Yes, I switch to using the old 8.x UI, and the `Kafka/Producer/Callback` is shown.

Hi @jmjoy, the bugfix has been merged to the master branch. You may have a try.

**Comment by jmjoy** [comment] 2022-07-05 08:19
> 

I just tested it and found it to be fixed.

> > Yes, I switch to using the old 8.x UI, and the `Kafka/Producer/Callback` is shown.
> 
> Hi @jmjoy, the bugfix has been merged to the master branch. You may have a try.

I just tested it and found it to be fixed.

**Comment by jmjoy** [comment] 2022-07-10 12:22
Add Tracer: <https://github.com/apache/skywalking-rust/pull/26>

**Comment by wu-sheng** [comment] 2022-07-16 09:59
Auto finalize context and span when dropped. https://github.com/apache/skywalking-rust/pull/28

**Comment by wu-sheng** [comment] 2022-07-16 10:00
We only have cross threads left for this issue, right?

**Comment by jmjoy** [comment] 2022-07-16 15:15
> We only have cross threads left for this issue, right?

Yes.

**Comment by wu-sheng** [comment] 2022-07-19 02:40
**Add context capture and continued methods.** through https://github.com/apache/skywalking-rust/pull/29

**Closed** 2022-07-19 02:40 UTC
Labels: feature, rust

**Comment by wu-sheng** [comment] 2022-07-19 02:41
@jmjoy Should we consider a 0.3.0 release? Any other things you may add?

In the future, I think log collecting and meter(Metrics) reports are good choices.

**Comment by jmjoy** [comment] 2022-07-19 02:57
> @jmjoy Should we consider a 0.3.0 release? Any other things you may add?
> 
> In the future, I think log collecting and meter(Metrics) reports are good choices.

No problem, future changes can be put into 0.4.0.

**Comment by wu-sheng** [comment] 2022-07-19 03:14
@jmjoy I could start the release, could you update the version declare with e2e dependency?

**Comment by jmjoy** [comment] 2022-07-19 03:15
> @jmjoy I could start the release, could you update the version declare with e2e dependency?

OK.

**Comment by xiaoniankang** [comment] 2022-08-01 07:52
> > 也许是一些可视化错误？我不确定这一点。因为这个 span 有两个引用，一个是 RPC peer，另一个是来自本地 span 的 snapshot。
> > 如果您纯粹想检查捕获和连续性，则所有异步 HTTP 调用或回调都应包括这种情况。
> 
> 我已经确认了 9.0.0 和 9.1.0 的问题。
> 
> 该问题是由于`EndpointDepFromCrossThreadAnalysisListener`在v9中引入的，在分析过程中抛出了NPE，那么该段将不会被保存到存储中。
> 
> ```
> org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler - 75 [grpcServerPool-1-thread-14] ERROR [] - null
> java.lang.NullPointerException: null
> 	at org.apache.skywalking.oap.server.core.source.EndpointRelation.prepare(EndpointRelation.java:101) ~[server-core-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.core.analysis.DispatcherManager.forward(DispatcherManager.java:59) ~[server-core-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.core.source.SourceReceiverImpl.receive(SourceReceiverImpl.java:36) ~[server-core-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener.lambda$build$0(EndpointDepFromCrossThreadAnalysisListener.java:130) ~[agent-analyzer-9.1.0.jar:9.1.0]
> 	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_332]
> 	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.listener.EndpointDepFromCrossThreadAnalysisListener.build(EndpointDepFromCrossThreadAnalysisListener.java:124) ~[agent-analyzer-9.1.0.jar:9.1.0]
> 	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_332]
> 	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.notifyListenerToBuild(TraceAnalyzer.java:75) ~[agent-analyzer-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.TraceAnalyzer.doAnalysis(TraceAnalyzer.java:71) ~[agent-analyzer-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.analyzer.provider.trace.parser.SegmentParserServiceImpl.send(SegmentParserServiceImpl.java:40) ~[agent-analyzer-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:72) [skywalking-trace-receiver-plugin-9.1.0.jar:9.1.0]
> 	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v8.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:63) [skywalking-trace-receiver-plugin-9.1.0.jar:9.1.0]
> 	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [grpc-stub-1.46.0.jar:1.46.0]
> 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318) [grpc-core-1.46.0.jar:1.46.0]
> 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301) [grpc-core-1.46.0.jar:1.46.0]
> 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834) [grpc-core-1.46.0.jar:1.46.0]
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.46.0.jar:1.46.0]
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.46.0.jar:1.46.0]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_332]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_332]
> 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
> ```

Has the 9.1.0 version of the official website been solved?  I still seem to have this problem with the 9.1.0 tar package I downloaded
