### ISSUE TITLE
Skywalking agent modifying bytecode and blocking collisions

### ISSUE THREAD

**Issue by 292292yang** [apache/skywalking#1317] opened 2018-06-07 04:09 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
___
### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 3.2.6  
OS win7
JRE jdk1.8
- Which company or project?
北京壹号车科技有限公司

- What happen?
 
   Demo in attach。
   If you add skywalking agent to tomcat, the following error will appear:
   `java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:662)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:213)
	at com.TestController.test$original$Oz7g7Vag(TestController.java:20)
	at com.TestController.test$original$Oz7g7Vag$accessor$X8Huy5Bp(TestController.java)
	at com.TestController$auxiliary$2azUNemA.call(Unknown Source)
	at org.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:92)
	at com.TestController.test(TestController.java)
	at com.TestController$$FastClassBySpringCGLIB$$ee5085fb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
`
   [api.zip](https://github.com/apache/incubator-skywalking/files/2078864/api.zip)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by wu-sheng** [comment] 2018-06-08 02:56
@ascrutae Does our plugin use the response?

**Comment by ascrutae** [comment] 2018-06-12 15:40
No,  In our plugin there is any plugin to operation  the `Response`, excepted to get the status code . But this demo make me confused. because it cannot reproduce this error in both of version 3.2.6 and version 5.0.0-beta

**Comment by ascrutae** [comment] 2018-06-12 15:41
@292292yang Are you sure that demo can produce this issue in your environment?

**Comment by wu-sheng** [comment] 2019-05-22 12:33
No update. Closing.

**Closed by wu-sheng** 2019-05-22 12:33 UTC
Labels: question
