### ISSUE TITLE
[Bug]  ERROR [] - [9.6.0-fb61128] LEAK: ByteBuf.release() was not  called before it's garbage-collected

### ISSUE THREAD

**Issue by gaogaoSpark** [apache/skywalking#11589] opened 2023-11-24 08:30 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

1.describe 
  - 3 oap-server instance,
  - agent: java,python,nginx
  - VIP redirect to 3 oap-server instance

2.start 

`
docker run --name skywalking --restart always -d --net=host --memory=24g \
-e TZ=Asia/Shanghai \
-e JAVA_OPTS="-Xms16g -Xmx16g" \
-e SW_STORAGE_ES_BATCH_OF_BYTES=20971520 \
-e SW_STORAGE=elasticsearch \
-e SW_STORAGE_ES_CLUSTER_NODES="es1:9200,es1:9200,es1:9200" \
-e SW_CLUSTER=zookeeper \
-e SW_NAMESPACE=skywalking \
-e SW_CLUSTER_ZK_HOST_PORT="zk1:2181,zk2:2181,zk3:2181" \
skywalking-oap-server:9.6.0
`
3.happened
`
2023-11-22 07:27:54,168 io.netty.util.ResourceLeakDetector 319 [grpcServerPool-1-thread-10] ERROR [] - [9.6.0-fb61128] LEAK: ByteBuf.release() was not 
called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:359)
	io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:140)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
`

### What you expected to happen

i think that some resource not be gc.

### How to reproduce

Optimize many parameters, but the problem still exists

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaogaoSpark** [comment] 2023-11-24 08:37
memory used:
![image](https://github.com/apache/skywalking/assets/16930471/b27691f6-c69b-48e3-9662-5138536a39e5)

**Comment by wu-sheng** [comment] 2023-11-24 11:11
We never used netty directly, do you check Armenia and/grpc bugs?

**Comment by gaogaoSpark** [comment] 2023-11-25 11:25
> We never used netty directly, do you check Armenia and/grpc bugs?

what do you mean Armenia?
This log is copy from skywalking

**Comment by wu-sheng** [comment] 2023-11-25 14:13
Armeria, a lib of HTTP, we are using for HTTP client and server.
GRPC and Armeria are using netty internally. SkyWalking doesn't use netty directly.

**Comment by wu-sheng** [comment] 2023-11-27 14:16
@gaogaoSpark Any update?

**Comment by gaogaoSpark** [comment] 2023-11-28 00:29
> @gaogaoSpark Any update?

I need time to test.  
The mem is very high and not decreased.
In addition, I didn't use kafka fetcher, and all three nodes are mixed mode.

**Comment by gaogaoSpark** [comment] 2023-11-28 00:32
> > @gaogaoSpark Any update?
> 
> I need time to test. The mem is very high and not decreased. In addition, I didn't use kafka fetcher, and all three nodes are mixed mode.

Is there any suggestion for the memory size? The current value is 24g.

**Comment by wu-sheng** [comment] 2023-11-28 00:48
24g should be good for most cases.

**Comment by kezhenxu94** [comment] 2023-11-28 03:09
Might be related to https://github.com/grpc/grpc-java/issues/9563, @gaogaoSpark can you verify whether https://github.com/apache/skywalking-java/pull/650 fixes the issue?

**Comment by wu-sheng** [comment] 2023-11-28 06:52
It is a client side issue? Or it is related to remote client in the OAP?

**Comment by kezhenxu94** [comment] 2023-11-28 07:06
> It is a client side issue? Or it is related to remote client in the OAP?

The OAP itself has the grpc version that contains the fix I posted, so it might not be related to the OAP remote client, while the java agent has not such fix, although I didn't find a clear clue about the issue is only related to client or server side, it's a fix in the `core` module of grpc.

**Comment by wu-sheng** [comment] 2023-11-28 07:15
OK. I am close this. If @gaogaoSpark has newly updated, comment here.

**Closed by wu-sheng** 2023-11-28 07:15 UTC
Labels: bug, backend, dependencies
