### ISSUE TITLE
[Bug] the `Aggregation` and `GC Count` metrics in `fetcher-prom-rules/self.yaml` and `otel-oc-rules/oap.yaml` are wrong

### ISSUE THREAD

**Issue by Cool-Coding** [apache/skywalking#8707] opened 2022-03-18 13:14 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

OAP server (apache/skywalking)

### What happened

```
 - name: instance_metrics_first_aggregation
    exp: metrics_aggregation.tagEqual('dimensionality', 'minute', 'level', '1').sum(['service', 'instance']).increase('PT5M')
  - name: instance_metrics_second_aggregation
    exp: metrics_aggregation.tagEqual('dimensionality', 'minute', 'level', '2').sum(['service', 'instance']).increase('PT5M')
```
 
The value of first and second aggregation are wrong.

### What you expected to happen

Both of first and second aggregation use the metrics_aggregation metric.  the increase method uses <code>org.apache.skywalking.oap.meter.analyzer.dsl.counter.CounterWindow</code> to calculate.

The CounterWindow class is a Singleton class.  it uses <code>Map</code> to store the window data. the Map key is combined by name and labels of a metric. but both of  first and second aggregation have the same metric name and labels. the metric name is "metrics_aggregation" and the labels are "service" and "instance".  this will result in that they will use the same window.

the increase method is as below

``` java
  public Tuple2<Long, Double> increase(String name, ImmutableMap<String, String> labels, Double value, long windowSize, long now) {
        ID id = new ID(name, labels);
        Queue<Tuple2<Long, Double>> window = windows.computeIfAbsent(id, unused -> new PriorityQueue<>());
        window.offer(Tuple.of(now, value));
        long waterLevel = now - windowSize;
        Tuple2<Long, Double> peek = window.peek();
        if (peek._1 > waterLevel) {
            return peek;
        }

        Tuple2<Long, Double> result = peek;
        while (peek._1 < waterLevel) {
            result = window.poll();
            peek = window.element();
        }

        // Choose the closed slot to the expected timestamp
        if (waterLevel - result._1 <= peek._1 - waterLevel) {
            return result;
        }

        return peek;
    }
```

The right configurations i think and have proved are as below.

- self.yaml in fetcher-prom-rules

> I delete the first and second aggregation and create a new metric named "instance_metrics_aggregation".

```
 - name: instance_metrics_aggregation
    exp: metrics_aggregation.tagEqual('dimensionality', 'minute').sum(['service', 'instance', 'level']).increase('PT5M').tag({tags -> if (tags['level'] == '1') {tags.level = 'first aggregation'} }).tag({tags -> if (tags['level'] == '2') {tags.level = 'second aggregation'} })

```

- self-observability in ui-initialized-templates

```
      {
        "width": "3",
        "title": "Aggregation",
        "height": "200",
        "entityType": "ServiceInstance",
        "independentSelector": false,
        "metricType": "LABELED_VALUE",
        "metricName": "meter_oap_instance_metrics_aggregation",
        "queryMetricType": "readLabeledMetricsValues",
        "chartType": "ChartBar",
        "unit": "Per 5 Minute"
      }
```

### How to reproduce

I have debuged in the increase method and watch the metric value in the ui page.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wu-sheng** [comment] 2022-03-18 13:54
Thanks for reporting. I think you should fix `otel-oc-rules/oap.yaml` as well.

I have assigned this to you, wait for your pull request. FYI @wankai123

**Comment by wu-sheng** [comment] 2022-03-18 14:13
@Cool-Coding Are you saying this is a bug of **window** for counter?

**Comment by wu-sheng** [comment] 2022-03-18 14:16
My understanding is, we need a better key for **increase**. ID should include metric name, labels and values. 

@hanahmily What do you think?

**Comment by wu-sheng** [comment] 2022-03-18 14:50
@Cool-Coding Have you tried this?

Change
> metrics_aggregation.tagEqual('dimensionality', 'minute', 'level', '1').sum(['service', 'host_name']).increase('PT1M')

to
> metrics_aggregation.tagEqual('dimensionality', 'minute', 'level', '1').sum(['service', 'host_name','level']).increase('PT1M')

**Comment by hanahmily** [comment] 2022-03-19 02:59
`CounterWindow` combines `ID` with metric name, label key, and label value. These two metrics' `level` label values are not identical, the first level is `1`, and the latter is `2`. Based on that, the window can't mess them up. But I didn't do some necessary verification. Would you pls provide more pieces of evidence about this?

**Comment by wu-sheng** [comment] 2022-03-19 03:00
The mass is caused by sum with labels, the level is gone. I think.

**Comment by hanahmily** [comment] 2022-03-19 03:26
> The mass is caused by sum with labels, the level is gone. I think.

maks sense. adding `level` to the `sum`'s parameter list might work.

**Comment by Cool-Coding** [comment] 2022-03-19 09:51
> The mass is caused by sum with labels, the level is gone. I think.
Yes, Your are right. there is not the "level" field in the sum. so  the labels in the increase method just contain "service" and "instance".

**Comment by Cool-Coding** [comment] 2022-03-19 09:52
> Thanks for reporting. I think you should fix `otel-oc-rules/oap.yaml` as well.
> 
> I have assigned this to you, wait for your pull request. FYI @wankai123

ok, I will look at the  `otel-oc-rules/oap.yaml`  and pull a request.

**Comment by wu-sheng** [comment] 2022-03-19 10:51
PT1M makes sense to me.

**Comment by Cool-Coding** [comment] 2022-03-21 05:58
@wu-sheng `Gc Count` metric is also wrong in `otel-oc-rules/oap.yaml` and `fetcher-prom-rules/self.yaml`. I also have fixed it and pull a request. please help me review. Thank you!

Let's take a look at the comparison of the trend chart before and after the modification.

Before:
![image](https://user-images.githubusercontent.com/29882506/159211273-f2cdd4a0-4bb2-4cab-b393-0a4e936fb8ed.png)

![image](https://user-images.githubusercontent.com/29882506/159211290-b8c499f5-4900-4d51-a3bc-f8919189a909.png)

After:
![image](https://user-images.githubusercontent.com/29882506/159211375-b004760e-8736-4529-b378-739f89443100.png)

![image](https://user-images.githubusercontent.com/29882506/159211389-7a22cfcc-7ce3-4aa0-88c8-22b6d72c1f91.png)

In general, before the modification, the value of the metric will become larger and larger over time. The value per minute exceeds the normal value

**Comment by wu-sheng** [comment] 2022-03-21 06:01
This looks good, just please rename `first aggregation` -> `L1 aggregation` and `second` -> `L2`. 

Also, make sure change logs includes both fixes in your pull request.

**Comment by Cool-Coding** [comment] 2022-03-21 06:32
> This looks good, just please rename `first aggregation` -> `L1 aggregation` and `second` -> `L2`.
> 
> Also, make sure change logs includes both fixes in your pull request.

@wu-sheng  Ok, I have changed the tag of `Aggregation` and pull a new request.

**Closed** 2022-03-21 11:03 UTC
Labels: bug, backend
