### ISSUE TITLE
add error log(log4j,logback) to span log event 

### ISSUE THREAD

**Issue by limfriend** [apache/skywalking#4545] opened 2020-03-20 08:36 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement
___
### Requirement or improvement
It is difficulty to correlate log and tracing.  
Finding tracing by traceId often fails because sampling is turned on.
if we record important log (such as error log or warning log) in tracing . it is easy to find what is problem in our service with sky walking.

**Comment by wu-sheng** [comment] 2020-03-20 08:38
I don't think there is much different, if you open sampling at the agent side, then the logs still are ignored like the traceid. They are sharing the same context basically.

**Comment by limfriend** [comment] 2020-03-20 10:02
> I don't think there is much different, if you open sampling at the agent side, then the logs still are ignored like the traceid. They are sharing the same context basically.
It is very easy to find errors in the existing system, and tracing through the error log is a hundred times only successful once when the sampling rate is 1%.

It is easy to find error log in skywalking if we add error log to span event.
It is  a hundred times only successful once with error traceId when the sampling rate is 1%.
We only need to care about which tracings are recorded abnormally, rather than looking for which records from all records one by one.
Just care about the recorded error span, not all the errors in the log, is efficient way.

**Comment by wu-sheng** [comment] 2020-03-20 10:10
Then you should consider to add a log plugin. We are welcome to take this as an optional plugin.
Based on our community principle, people contribute the featured they want.

**Comment by wu-sheng** [comment] 2020-03-20 10:11
Also, if you add this, ithere is a potential performance and network impact. Be careful.

**Comment by vcjmhg** [comment] 2020-09-28 12:37
Is anyone currently developing this plugin?:smile:

**Comment by wu-sheng** [comment] 2020-09-28 13:00
@vcjmhg I assigned to you. Thanks for helping.

**Comment by vcjmhg** [comment] 2020-09-28 13:08
ok,I will do it.

**Comment by vcjmhg** [comment] 2020-10-01 06:35
@wu-sheng ,Sir, I have a problem about this plugin.Users may be configure more than one appender to collect logs , just like this:
```xml
<configuration>
  <appender name="FILE" class="ch.qos.logback.core.FileAppender">
    <file>myApp.log</file>
    <encoder>
      <pattern>%date %level [%thread] %logger{10} [%file:%line] %msg%n</pattern>
    </encoder>
  </appender>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%msg%n</pattern>
    </encoder>
  </appender>

  <root level="debug">
    <appender-ref ref="FILE" />
    <appender-ref ref="STDOUT" />
  </root>
</configuration>
```
From the above file, you can see that the user used two appenders with different patterns to collect the same log. So I want to know when plugin add error log to span log, should it add all error logs from the two appenders to the span log or just one of them?

**Comment by wu-sheng** [comment] 2020-10-01 13:58
From my understanding, we should not care what these config files say. I would suggest we intercept the `log#error` APIs directly, and provide the config file by following our own design. Such as, which levels, package names of logs, and what kinds of the format we should include. Using the format definition would definitely face the issue you mentioned.

**Comment by vcjmhg** [comment] 2020-10-02 06:27
ok, I will design a file in the same level directory of the plugin to filter the log categories that need to be recorded.

**Comment by vcjmhg** [comment] 2020-10-02 06:51
The config file may be just like this:
```yaml
logger:log4j/log4j2/logbak #defalut include all 
  package: package name(for exampleorg.apache.skywalking) 
  level: trace/debug/info/error
  parttern: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
```
If the user does not provide a configuration file, the plugin will record all error level logs. Is it ok to design the log plugin?

**Comment by wu-sheng** [comment] 2020-10-02 08:01
What kind of format is this layout? It seems like a YAML but it isn't. Please use the standard format, such as yaml/properties/xml

**Comment by vcjmhg** [comment] 2020-10-02 08:43
Just like this,is it ok?
```yaml
logger:
  - name: "log4j2"
    package: ["package1","package2","package3"]
    level: "trace"
    pattern: ["Regular expression1","Regular expression2"]
  - name: "log4j2"
    package: ["package3","package4"]
    level: "error"
    pattern: ["Regular expression"]
```

**Comment by wu-sheng** [comment] 2020-10-02 08:45
Prefer `package: ["package1","package2","package3"]` to the standard array format like this
```yaml
packages:
   - package1
   - package2
   - package3
```

**Comment by vcjmhg** [comment] 2020-10-02 08:50
Is this ok?
```yaml
logger:
  - name: "log4j2"
    packages:
      - package1
      - package2
    level: "trace"
    patterns: ["Regular expression1","Regular expression2"]
  - name: "logbak"
    packages:
      - package3
    level: "error"
    patterns: ["Regular expression"]
```

**Comment by wu-sheng** [comment] 2020-10-02 08:52
What do you mean by an array of the pattern? What is the case of multiple expressions?

**Comment by vcjmhg** [comment] 2020-10-02 09:03
As following logbak config file show, the config file define two appenders which has different pattern.If user want to colloct all of them , they may need use multiple expressions.Of course,user can use "|" to instead it in one regular expression .
```xml
<configuration>
  <appender name="FILE" class="ch.qos.logback.core.FileAppender">
    <file>myApp.log</file>
    <encoder>
      <pattern>%date %level [%thread] %logger{10} [%file:%line] %msg%n</pattern>
    </encoder>
  </appender>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%msg%n</pattern>
    </encoder>
  </appender>

  <root level="debug">
    <appender-ref ref="FILE" />
    <appender-ref ref="STDOUT" />
  </root>
</configuration>
```

**Comment by wu-sheng** [comment] 2020-10-02 09:05
I don't think our way has anything related to the appender. Could you explain why?

**Comment by vcjmhg** [comment] 2020-10-02 09:10
My initial idea is to use the `doAppender(E e)` method as an insertion point, and then judge and convert the information according to the requirements of the configuration file.

**Comment by vcjmhg** [comment] 2020-10-02 09:12
Because when after exec the "doAppender()",the logs is assembled.

**Comment by wu-sheng** [comment] 2020-10-02 09:14
As we have our own config file, why need this? Why don't intercept `log#error` directly?

**Comment by vcjmhg** [comment] 2020-10-02 09:49
If intercept `log#error` directly, the content of logs that we can get is unformatted. 
```java
logger.error("hello world");
```
**unformatted logs:** 
hello world
**formatted logs:**
16:06:09.046 [main] INFO  chapters.configuration.MyApp1 - hello world.
Is it enough to add unformatted logs to the span log?

**Comment by wu-sheng** [comment] 2020-10-02 09:57
I think we take the responsibility to format, as we provided file, do you remember why we are discussing about adding our config file? If we use the original format, why need ours?

**Comment by wu-sheng** [comment] 2020-10-02 09:58
If there is original API we could call to format the message, it is fine. My point is, we are controlling the format.

**Comment by vcjmhg** [comment] 2020-10-02 10:11
ok, I got it. If do so, we should add an attribute named `filter` to filter the logs with regular expression. And the `pattern` to control the formate of the logs.Just like this:
```yaml
logger:
  - name: "log4j2"
    packages:
      - package1
      - package2
    level: "trace"
    pattern: "%date %level [%thread] %logger{10} [%file:%line] %msg%n"
    filter:"Regular expression"
  - name: "logbak"
    packages:
      - package3
    level: "error"
    patterns: "%msg%n"
    filter:"Regular expression"
```
Is it ok?

**Comment by wu-sheng** [comment] 2020-10-02 14:09
Please use `expression` to replace `filter`, which seems to make more sense.

**Comment by vcjmhg** [comment] 2020-10-02 14:11
ok, I got it.

**Comment by BFergerson** [comment] 2020-11-17 21:18
I have interest in this issue and would be willing to offer help. @vcjmhg, are you able to share any work you've done so far?

**Comment by vcjmhg** [comment] 2020-11-18 02:49
Sir, there were a lot of laboratory tasks some time ago, so the progress was a bit slow. Currently, I have written a simple document, and some verification work has not been completed.
**The directory of plugin-in** is ` https://github.com/vcjmhg/skywalking/tree/f-log/apm-sniffer/apm-sdk-plugin/logger-plugin`
**The directory of test** is  `https://github.com/vcjmhg/skywalking/tree/f-log/test/plugin/scenarios/logger-scenario`
The design document will be sent to you after the translation is completed.

**Comment by vcjmhg** [comment] 2020-11-18 05:05
# Summary

The plug-in can store the logs generated by the program during the call, such as the content of the error log, into the span log. And the plug-in provides matching files. Through the configuration file, you can control the log source (log4j2, logbak, log4j), package name, level, and content that need to be stored in the span log, and you can customize the log format saved to the span log. .

# Configuration file

`logfilter.yaml`

```yaml
  - name: "lo2"
    packages:
      - package1
      - package2
    level: "trace"
    pattern: "
    "
    expression: "Regular expression"
  - name: "logbak"
    packages:
      - package3
    level: "error"
    patterns: "%msg%n"
    expression: "Regular expression"
```

# Field description

**name attribute**: Specify the log system that needs to perform log conversion. If you use a configuration file for configuration, the name must be written.

There are four values for name:

* log4j
* log4j2
* logbak
* `*`:Match all supported log

**package attribute**: Specify the package name of the log that needs log conversion. When using the configuration file for configuration, it can be defaulted. If the default is stupid with `*`, it will match all packages.

`package value`:

* the name of package, eg: `org.apache.skywalking`
* `*`:match all 

**level attribute**: The level of the log for conversion. **By default it is `error` level**

* trace
* debug
* info
* error

**patterns attribute:** used to control the format of the log written to the span log

The control method of the specific format, refer to logbak, for details, please refer to http://logback.qos.ch/manual/layouts.html

**expression attribute**: filter logs that need to be converted into lspan log. This attribute accepts a regular expression, the content of the log body will be matched, if it is matched, then input, otherwise no conversion will be performed. **By default, it matches all, that is, no filtering is performed. **

# Realization idea

1. Analyze the configuration file and fill it into a  instance of `loggerConfig`, which contains a List to store Logger, which is a record of configuration information of the logging system.

2. After the error method is intercepted, the log level will be determined according to the configuration file. **If the level requirements are met**, the regular expression filtering will begin. If the filtering requirements are met, the instance of `LogEvent` will be created. After filling, execute the formate method to format the log information.

   **Formatting operation method (modeled on PatternLayout to realize log analysis):**

   1. The `LoggerFactory.getLogger()` method is enhanced to obtain the logger object. And then get the  object of `LoggerContext` .

      ```java
      Logger logger = LoggerFactory.getLogger(CaseController.class);
              ch.qos.logback.classic.Logger myLogger = (ch.qos.logback.classic.Logger) logger;
              LoggerContext context = myLogger.getLoggerContext();
      ```

   2. Rewrite a suitable Appender or use `PatternLayoutEncorder` directly to format the required information

      ```java
       Logger rootLogger = (Logger)LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
          LoggerContext loggerContext = rootLogger.getLoggerContext();
          // we are not interested in auto-configuration
          loggerContext.reset();
      
          PatternLayoutEncoder encoder = new PatternLayoutEncoder();
          encoder.setContext(loggerContext);
          encoder.setPattern("%-5level [%thread]: %message%n");
          encoder.start();
      
          ConsoleAppender<ILoggingEvent> appender = new ConsoleAppender<ILoggingEvent>();
          appender.setContext(loggerContext);
          appender.setEncoder(encoder); 
          appender.start();
      
          rootLogger.addAppender(appender);
      
          rootLogger.debug("Message 1");
          rootLogger.warn("Message 2");
      ```

3. After the operation is completed, initialize the instance of `ContextCarrier` to obtain the span and then place the corresponding information in the `spanlog`

4. Stop `sapn`

# Some problems

1. `LogbakLoggerFactoryInstrumentation` is not working well and I can't get the the instance of `org.slf4j.LoggerFactory`.Now I am fixing it.
2. The function of formatting the log has not been fully completed yet.

**Comment by BFergerson** [comment] 2020-11-18 17:43
@vcjmhg, thanks for all of the above information. It is very helpful.

I've taken a look at the work you've done and it does seem to be pretty much there for Logback. Btw, you have `logbak` written in multiple places and I think you meant `logback`. I can submit this fix and a few other code cleaning refactors if you like.

I have some questions which would be helpful for me to contribute to this task:
- Why does `LogbakLoggerFactoryInstrumentation` need to know about `org.slf4j.LoggerFactory`?
   - I would assume slf4j wouldn't come into the picture as under the hood it is using other logging frameworks. As long as those logging frameworks are supported I don't see why there would need to be any code related to slf4j.
- How did you plan on testing all of these logging frameworks?
  - The test class you've created depends on spring-boot-starter-web which defaults to logback. Did you plan on testting all logging frameworks under this one scenario or did you plan on testing one logging framework per scenario? If so maybe `logger-scenario` is too broad as is.
- Why save `LoggerContext` to a thread local map instead of pulling it from `objInst`?
- What's the need for starting and stopping a span for adding logging?
   - Couldn't you just do `if (ContextManager.isActive()) ContextManager.activeSpan().log(...)`
 - What format did you have in mind for logging to spans?
   - `AbstractSpan` only has `log(Throwable)` and `log(long, Map<String, ?>)`. What type of map would you put there? Just a single key/value map with a key of `data` and the log saved to value?

Apologies if that's a lot of questions. I'm just trying to get on the same page as you so I can help more effectively.

**Comment by vcjmhg** [comment] 2020-11-19 02:30
> Why does `LogbakLoggerFactoryInstrumentation` need to know about `org.slf4j.LoggerFactory`?
> * I would assume slf4j wouldn't come into the picture as under the hood it is using other logging frameworks. As long as those logging frameworks are supported I don't see why there would need to be any code related to slf4j.

 1. Through the LogContext instance, We can obtain some information that cannot be directly obtained by intercepting the `logger.trace()` method,  such as the package name, the stack trace of the exception associated with the logging event.
2. And if we want to use PatternLayoutEncoder to fully support the formatting function, the LogContext instance is also necessary. Of course, if we can obtain the necessary information through other methods, we can implement the formatting function ourselves
If you have a better idea to obtain the necessary information, please put it forward and we will verify it together. Thank you!

**Comment by vcjmhg** [comment] 2020-11-19 02:45
> How did you plan on testing all of these logging frameworks?
> * The test class you've created depends on spring-boot-starter-web which defaults to logback. Did you plan on testting all logging frameworks under this one scenario or did you plan on testing one logging framework per scenario? If so maybe `logger-scenario` is too broad as is.
Yes, I want to test one logging framework per scenario. And every scenario will be a submodule under `logger-scenario`.The `logger-scenario` project is automatically generated through a script, so it seems a bit strange, I will modify it later.

**Comment by vcjmhg** [comment] 2020-11-19 03:02
> * Why save `LoggerContext` to a thread local map instead of pulling it from `objInst`?

I don't quite understand what does `objInst` mean? Any method as long as it can obtain an instance of `logContext` will be ok. The reason why save `LoggerContext` to a thread-local map is to we can use it when we format log messages in `org.apache.skywalking.apm.plugin.logger.LogbakLoggerInterceptor`.

**Comment by BFergerson** [comment] 2020-11-19 03:02
> > Why does `LogbakLoggerFactoryInstrumentation` need to know about `org.slf4j.LoggerFactory`?
> > 
> > * I would assume slf4j wouldn't come into the picture as under the hood it is using other logging frameworks. As long as those logging frameworks are supported I don't see why there would need to be any code related to slf4j.
> 
>     1. Through the LogContext instance, We can obtain some information that cannot be directly obtained by intercepting the `logger.trace()` method,  such as the package name, the stack trace of the exception associated with the logging event.
> 
>     2. And if we want to use PatternLayoutEncoder to fully support the formatting function, the LogContext instance is also necessary. Of course, if we can obtain the necessary information through other methods, we can implement the formatting function ourselves
>        If you have a better idea to obtain the necessary information, please put it forward and we will verify it together. Thank you!

I'm still not seeing why there is a need for knowledge about slf4j. What if someone uses Logback without using slf4j? I would think that means this plugin would no longer work.

Also, I've confirmed that the exact instance which is being stored in `LOCAL_LOGGER_CONTEXT` is what is available in `EnhancedInstance` on `LogbackLoggerInterceptor`. This evaulates to true:
```
LoggerContextUtil.LOCAL_LOGGER_CONTEXT.get() == ((Logger)((Object) objInst)).getLoggerContext()
```
Given you change `LogbackLoggerFactoryInstrumentation.ENHANCE_CLASS` to `ch.qos.logback.classic.LoggerContext`.

**Comment by vcjmhg** [comment] 2020-11-19 03:05
> What's the need for starting and stopping a span for adding logging?
> * Couldn't you just do `if (ContextManager.isActive()) ContextManager.activeSpan().log(...)`

Your method is better, I didn’t think of it before, forgive me for being a novice. :smile:

**Comment by vcjmhg** [comment] 2020-11-19 03:12
> What format did you have in mind for logging to spans?
> * `AbstractSpan` only has `log(Throwable)` and `log(long, Map<String, ?>)`. What type of map would you put there? Just a single key/value map with a key of `data` and the log saved to value?

Yes, I will use  `log(long, Map<String, ?>)`. The key is the name of log systems such as logbak or log4j. And its value is the content of the log message. If you have a better idea, you are also welcome to come and discuss it together

**Comment by BFergerson** [comment] 2020-11-19 03:13
It took me a second to figure out how to get `EnhancedInstance` to `Logger` too lol. This is probably the first time I've come across a situation where double casting was necessary.

**Comment by wu-sheng** [comment] 2020-11-19 03:31
Please submit an issue or pull request about the definition of logging integration, specific keys and values.

**Closed** 2020-12-10 05:53 UTC
Labels: agent, good first issue, plugin
