### ISSUE TITLE
[Bug] banyandb web-ui console error logs

### ISSUE THREAD

**Issue by hailin0** [apache/skywalking#11273] opened 2023-08-29 02:22 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

BanyanDB (apache/skywalking-banyandb)

### What happened

When switching resource card pages, the exception log is output on the console

### What you expected to happen

no error logs

### How to reproduce

https://github.com/apache/skywalking/assets/14371345/9ba4aaa4-47fe-41dd-a4ea-fefac9b65e85

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by sksDonni** [comment] 2024-02-28 18:00
Hi @hanahmily and @hailin0, would like to take this up. But not sure why, but I am not able to reproduce this in my local setup.
I am using a M1 mac running the standalone deployment of banyanDB. I created all groups, streams and measures using the banyanDB java client. 
Have attached a screengrab - 
https://github.com/apache/skywalking/assets/53624363/da45c28e-67d9-4d73-a12e-18dac0fd4ad1

Please let me know if you are still facing this issue, or is there some issue from my end.

**Comment by hanahmily** [comment] 2024-02-28 23:42
I couldn't find any errors upon double-checking. Could you verify, @hailin0?

**Comment by hailin0** [comment] 2024-02-29 05:40
<img width="1181" alt="image" src="https://github.com/apache/skywalking/assets/14371345/110a3137-0563-45fd-8f0c-194a738d0b0e">

**Comment by hanahmily** [comment] 2024-02-29 05:42
@sksDonni To merge the issue, please open two tabs and switch between them.

**Comment by sksDonni** [comment] 2024-02-29 17:26
Got it @hanahmily, the error is reproducible when we try to read two different measures. Can you please assign this ticket to me.

**Comment by wu-sheng** [comment] 2024-03-12 06:33
Fixed by https://github.com/apache/skywalking-banyandb/pull/408

**Closed by wu-sheng** 2024-03-12 06:33 UTC
Labels: bug, UI, database
