### ISSUE TITLE
Used  msyql ,After a few minutes ,No data

### ISSUE THREAD

**Issue by chad0329** [apache/skywalking#4193] opened 2020-01-07 09:11 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ * ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
 SkyWalking:6.5.0
JDK:1.8
mysql:5.7

- Which company or project?
Used  msyql ,After a few minutes ,no data

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
![image](https://user-images.githubusercontent.com/56951099/71883080-9be81d80-3170-11ea-9977-e916eec518a1.png)
![image](https://user-images.githubusercontent.com/56951099/71883112-ac989380-3170-11ea-8274-5fc89b98ae76.png)

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment] 2020-01-07 09:59
Duplicate of #4153

**Closed by kezhenxu94** 2020-01-07 09:59 UTC
