### ISSUE TITLE
Can't run skywalking on k8s with Elasticsearch authorized by SW_ES_USER && SW_ES_PASSWORD

### ISSUE THREAD

**Issue by totemofwolf** [apache/skywalking#4792] opened 2020-05-16 08:12 UTC
- Why do you submit this issue?

- [x] Bug

___
### Bug
- Which version of SkyWalking, OS and JRE?

docker images:
apache/skywalking-oap-server:7.0.0-es7
apache/skywalking-ui:7.0.0

- What happen?

```
docker image: apache/skywalking-oap-server:7.0.0-es7

oap-server deployment with:

        env:
        - name: JAVA_OPTS
          value: "-Xmx4g -Xms4g"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "skywalking-prod"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking,release=skywalking-prod,component=skywalking-oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch7
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: elastic-es-http:9200
        # - name: SW_ES_USER
        #   value: "sw_user"
        # - name: SW_ES_PASSWORD
        #   value: "PASSWORD"
        - name: SW_STORAGE_ES_SSL_JKS_PATH
          value: ""
        - name: SW_STORAGE_ES_SSL_JKS_PASS
          value: ""
        - name: SW_SW_STORAGE_ES_SSL_JKS_PATH
          value: ""
        - name: SW_SW_STORAGE_ES_SSL_JKS_PASS
          value: ""
        - name: TZ
          value: "Asia/Shanghai"

Return:

2020-05-16 14:44:30,632 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -11457 [main] INFO  [] - elasticsearch cluster nodes: elastic-es-http:9200
2020-05-16 14:44:32,146 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -12971 [main] ERROR [] - method [HEAD], host [http://elastic-es-http:9200], URI [/], status line [HTTP/1.1 401 Unauthorized]
org.elasticsearch.ElasticsearchStatusException: method [HEAD], host [http://elastic-es-http:9200], URI [/], status line [HTTP/1.1 401 Unauthorized]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1680) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:677) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.connect(ElasticSearch7Client.java:96) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:216) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://elastic-es-http:9200], URI [/], status line [HTTP/1.1 401 Unauthorized]
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212) ~[elasticsearch-rest-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]


```

___

```
oap-server deployment with:

        env:
        - name: JAVA_OPTS
          value: "-Xmx4g -Xms4g"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "skywalking-prod"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking,release=skywalking-prod,component=skywalking-oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch7
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: elastic-es-http:9200
        - name: SW_ES_USER
          value: "sw_user"
        - name: SW_ES_PASSWORD
          value: "PASSWORD"
        - name: SW_STORAGE_ES_SSL_JKS_PATH
          value: ""
        - name: SW_STORAGE_ES_SSL_JKS_PASS
          value: ""
        - name: SW_SW_STORAGE_ES_SSL_JKS_PATH
          value: ""
        - name: SW_SW_STORAGE_ES_SSL_JKS_PASS
          value: ""
        - name: TZ
          value: "Asia/Shanghai"

Return:

2020-05-16 14:48:42,733 - org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient -12441 [main] INFO  [] - elasticsearch cluster nodes: elastic-es-http:9200
2020-05-16 14:48:42,756 - org.apache.skywalking.oap.server.starter.OAPServerBootstrap -12464 [main] ERROR [] - ../es_keystore.jks
org.apache.skywalking.oap.server.library.module.ModuleStartException: ../es_keystore.jks
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:224) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.module.BootstrapFlow.start(BootstrapFlow.java:58) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.library.module.ModuleManager.init(ModuleManager.java:69) ~[library-module-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerBootstrap.start(OAPServerBootstrap.java:43) [server-bootstrap-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.starter.OAPServerStartUp.main(OAPServerStartUp.java:27) [server-starter-es7-7.0.0.jar:7.0.0]
Caused by: java.nio.file.NoSuchFileException: ../es_keystore.jks
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_212]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_212]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_212]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_212]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_212]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_212]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_212]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_212]
	at org.apache.skywalking.oap.server.library.client.elasticsearch.ElasticSearchClient.createClient(ElasticSearchClient.java:151) ~[library-client-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.client.ElasticSearch7Client.connect(ElasticSearch7Client.java:95) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
	at org.apache.skywalking.oap.server.storage.plugin.elasticsearch7.StorageModuleElasticsearch7Provider.start(StorageModuleElasticsearch7Provider.java:216) ~[storage-elasticsearch7-plugin-7.0.0.jar:7.0.0]
	... 4 more

```
___

**Comment by kezhenxu94** [comment] 2020-05-16 08:34
Duplicate of #4613

@totemofwolf can you have a look at #4613 and check the master branch to see whether it's fixed for you?

**Comment by wu-sheng** [comment] 2020-05-16 08:34
Duplicated. This is jks default value issue. Please report the issue after you search the existing.

**Closed by kezhenxu94** 2020-05-16 08:34 UTC

**Comment by totemofwolf** [comment] 2020-05-16 08:46
> Duplicate of #4613
> 
> @totemofwolf can you have a look at #4613 and check the master branch to see whether it's fixed in your case?

Yep. I have noticed that issue #4613 before submit this issue, and I just wandering whether  docker  image `apache/skywalking-oap-server:7.0.0-es7` contain this patch #4635  . I will try to manual patch #4635 and re-build a self-signed `skywalking-oap-server:7.0.0-es7`

**Comment by totemofwolf** [comment] 2020-05-16 08:47
> Duplicate of #4613
> 
> @totemofwolf can you have a look at #4613 and check the master branch to see whether it's fixed in your case?

3Q @wu-sheng ;-)

**Comment by wu-sheng** [comment] 2020-05-16 09:41
The image wouldn't changed based on ASF release policy. So, either file a new release or wait for the next official one.
