### ISSUE TITLE
[Bug] python log_reporter_level='INFO' is not work when start with django uWSGI

### ISSUE THREAD

**Issue by ysy1418899560** [apache/skywalking#8854] opened 2022-04-12 03:50 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/skywalking/issues?q=is%3Aissue) and found no similar issues.

### Apache SkyWalking Component

Python Agent (apache/skywalking-python)

### What happened

The params log_reporter_level='INFO' is not work when start with django uWSGI，on the UI only collect ERROR log, but cant collect INFO log。
python==3.7.9
django==3.2.7
uwsgi==2.0.19.1
apache-skywalking==0.7.0
skywalking version is 8.7.0

This is my code:
from skywalking import agent, config
from uwsgidecorators import postfork

@postfork
def init_tracing():
    config.init(collector_address='127.0.0.1:11800', service_name='video_processor', log_reporter_active=True,
                log_reporter_level='INFO', django_collect_http_params=True)
    agent.start()
![D840AF15-993A-442f-9094-447210C24595](https://user-images.githubusercontent.com/63773628/162875368-19acad4f-3017-4064-94f4-7f808b9e62f5.png)

### What you expected to happen

I hope set the params log_reporter_level='INFO' can collect info level log, and clicking the trace id will jump to the tracking interface when statr with django uWSGI。

### How to reproduce

python==3.7.9
django==3.2.7
uwsgi==2.0.19.1
apache-skywalking==0.7.0
skywalking version is 8.7.0

Below is my code:
from skywalking import agent, config
from uwsgidecorators import postfork

@postfork
def init_tracing():
    config.init(collector_address='127.0.0.1:11800', service_name='video_processor', log_reporter_active=True,
                log_reporter_level='INFO', django_collect_http_params=True)
    agent.start()

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Superskyyy** [comment] 2022-04-12 04:34
@ysy1418899560 Hello, thank you for reporting the potential bug! I will be looking into this and try reproduce the problem.

**Comment by ysy1418899560** [comment] 2022-04-12 05:35
It can collects info level log without uwsgi on my side，but the generated trace id is different between on log interface and tracking interface。Trace id is '8074295ba1f11eca9c6f8281960ba1c' on tracking interfacee，but on log interface is 
'ec28b995ba1f11ec91def8281960ba1c'。Pages cannot jump to each other。
![1](https://user-images.githubusercontent.com/63773628/162887876-18fa383b-bd48-4453-8c81-1881ee1bdc33.png)
![2](https://user-images.githubusercontent.com/63773628/162887884-c4f63a08-9db1-44f4-b394-930d7cabbdc7.png)

**Comment by Superskyyy** [comment] 2022-04-12 05:36
> It can collects info level log without uwsgi on my side，but the generated trace id is different between on log interface and tracking interface。Trace id is '8074295ba1f11eca9c6f8281960ba1c' on tracking interfacee，but on log interface is 'ec28b995ba1f11ec91def8281960ba1c'。Pages cannot jump to each other。 ![1](https://user-images.githubusercontent.com/63773628/162887876-18fa383b-bd48-4453-8c81-1881ee1bdc33.png) ![2](https://user-images.githubusercontent.com/63773628/162887884-c4f63a08-9db1-44f4-b394-930d7cabbdc7.png)

Thanks for the update, I'm looking into it now.

**Comment by Superskyyy** [comment] 2022-04-12 06:08
Update: I reproduced the reported issue on uwsgi post forked agent. I will try to figure out what is the cause.
Seems like anything below `WARNING` level is not reported regardless of the agent settings.

**Comment by ysy1418899560** [comment] 2022-04-12 08:37
Thanks for you，l will try this method。Please help to solve another issues that the trace id is inconsistency without uwsgi。Pages cannot jump to each other by trace id。

**Comment by Superskyyy** [comment] 2023-02-04 01:30
The invalid traceID problem is solved in https://github.com/apache/skywalking-python/pull/272 and other parts are coming in the pre-fork support. So closing this issue.

**Closed** 2023-02-04 01:30 UTC
Labels: documentation, good first issue, python
