### ISSUE TITLE
parser.SegmentParseV2 - 114 [grpc-default-executor-1] ERROR [] - null java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by quanquan-dane** [apache/skywalking#2988] opened 2019-07-03 01:07 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√] Question or discussion
- [√] Bug
___
### Question
- What do you want to know?
How to solve this problem。
___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking6.2
ElasticSearch-6.3.2
Linux【ubuntu 14 LTS】
JDK_1.8.0_161
- Which company or project?

- What happen?
2019-07-02 20:14:11,271 - org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2 - 114 [grpc-default-executor-1] ERROR [] - null
java.lang.NullPointerException: null
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener.setPublicAttrs(MultiScopesSpanListener.java:203) ~[skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.listener.endpoint.MultiScopesSpanListener.parseEntry(MultiScopesSpanListener.java:117) ~[skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.lambda$notifyEntryListener$1(SegmentParseV2.java:221) ~[skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_162]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.notifyEntryListener(SegmentParseV2.java:219) ~[skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.preBuild(SegmentParseV2.java:183) ~[skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2.parse(SegmentParseV2.java:92) [skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.parser.SegmentParseV2$Producer.send(SegmentParseV2.java:270) [skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:58) [skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at org.apache.skywalking.oap.server.receiver.trace.provider.handler.v6.grpc.TraceSegmentReportServiceHandler$1.onNext(TraceSegmentReportServiceHandler.java:50) [skywalking-trace-receiver-plugin-6.2.0.jar:6.2.0]
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:248) [grpc-stub-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:683) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.15.1.jar:1.15.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.15.1.jar:1.15.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by kezhenxu94** [comment] 2019-07-03 01:13
Duplicate of #2224

**Closed by kezhenxu94** 2019-07-03 01:13 UTC
