### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by SummerOfServenteen** [apache/skywalking#2926] opened 2019-06-21 09:51 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
SkyWalking：6.1.0,jre:1.8
- Which company or project?
jingling
- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by kezhenxu94** [comment] 2019-06-21 10:12
@SummerOfServenteen Can you provide more information?

**Comment by wu-sheng** [comment] 2019-06-21 10:16
@kezhenxu94 We only set version if we plan to accept PR. Before that, we discuss.

**Comment by SummerOfServenteen** [comment] 2019-06-21 10:20
hello.When we use skyWalking ,it cause Java heap space。after analyze the dump file ,we find it's conflict with Sentinel. 
Here is the detail.

![image](https://user-images.githubusercontent.com/31895647/59915229-bb2a9200-944e-11e9-945b-7c0fb19c6e0e.png)
![image](https://user-images.githubusercontent.com/31895647/59915288-dac1ba80-944e-11e9-8ba3-845a6d6b7322.png)
![image](https://user-images.githubusercontent.com/31895647/59915318-edd48a80-944e-11e9-9dbd-d19f2bdcf66b.png)
![image](https://user-images.githubusercontent.com/31895647/59915331-f62cc580-944e-11e9-81a0-724721955ffb.png)
Finally,i find it's method of org.apache.skywalking.apm.agent.core.context.util.ThrowableTransformer.convert2String that cause outOfMemory .

Code analyzing...
![image](https://user-images.githubusercontent.com/31895647/59915716-e3ff5700-944f-11e9-8ed0-da89195e24b1.png)
![image](https://user-images.githubusercontent.com/31895647/59915738-ee215580-944f-11e9-8792-d7d0639e7e77.png)

Because of Sentinel had overWrite the method of  fillInStackTrace(),so the stackTrace of size is 0,
the return value of printStackElement is always false.Then the method of convert2String is in Infinite loop.

My idea is rewrite the method of printStackElement like this :
![image](https://user-images.githubusercontent.com/31895647/59916195-15c4ed80-9451-11e9-977e-98be9975a40e.png)

**Comment by SummerOfServenteen** [comment] 2019-06-21 10:29
@wu-sheng,@kezhenxu94,can you help me to solve this problem~

**Comment by kezhenxu94** [comment] 2019-06-21 10:29
@SummerOfServenteen Thanks for reporting and elaborate on this, seems you've found a solution, could you please send a pull request to fix this?

**Comment by SummerOfServenteen** [comment] 2019-06-21 10:30
👌

**Comment by kezhenxu94** [comment] 2019-06-21 11:12
I'll take a look at the issue tomorrow

**Comment by wu-sheng** [comment] 2019-06-21 11:20
Why don't we fix append listenser bug and make the overMaxLength works?

**Comment by wu-sheng** [comment] 2019-06-21 14:32
Quote from expert

1. Worst case: little memory and very deep stack.
1. Use StackWalker and unsafe API before Java 9.
1. Like Sentinel, do intentionally.

I will raise a PR to make a better fix.

**Comment by wu-sheng** [comment] 2019-06-21 14:48
@SummerOfServenteen @kezhenxu94 Please review #2931

**Comment by Arugal** [comment] 2019-06-21 15:36
https://github.com/apache/skywalking/blob/fa7a1983f9be13280a3d5842a6b99d6b5c43563a/apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/util/ThrowableTransformer.java#L50

This is a weird line @wu-sheng

**Comment by wu-sheng** [comment] 2019-06-21 15:47
Why get the cause for deeper stack is weird? In this case, they create a self-ref, which cause OOM only.

**Comment by Arugal** [comment] 2019-06-21 15:53
Looks like the same ```throwable``` is returning

**Comment by wu-sheng** [comment] 2019-06-21 16:01
Good catch. That is a bug. I will fix that.

**Comment by wu-sheng** [comment] 2019-06-23 00:42
Merged. @SummerOfServenteen Could you try the master branch?

**Closed by wu-sheng** 2019-06-23 00:42 UTC
Labels: agent, bug

**Comment by SummerOfServenteen** [comment] 2019-06-23 02:59
could you please tell me what's the time of your next publication?

**Comment by wu-sheng** [comment] 2019-06-23 03:01
I hope I could froze codes next week.

**Comment by SummerOfServenteen** [comment] 2019-06-23 03:03
I and my co-workers tried to package a few days ago, he had said that in qq group 2

**Comment by SummerOfServenteen** [comment] 2019-06-23 03:05
I and my co-worker tried to package a few days ago, but it always failed and  he had said that in qq group 2

**Comment by wu-sheng** [comment] 2019-06-23 03:06
How fail? There are many messages every day. I can't follow all.
CI checked package for every merge. Should be fine.
