### ISSUE TITLE
i can't find 0.5.0 in npm repository

### ISSUE THREAD

**Issue by dgy5554** [apache/skywalking#6941] opened 2021-05-14 07:04 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
from https://github.com/apache/skywalking/issues/6940

i can't find 0.5.0 in npm repository
https://www.npmjs.com/package/skywalking-client-js

**Comment by kezhenxu94** [comment] 2021-05-14 07:04
Please don't open duplicated issue, 0.5.0 is under release process. Subscribe to mailing list to get the status

**Comment by kezhenxu94** [comment] 2021-05-14 07:05
Duplicate of #6940

**Closed by kezhenxu94** 2021-05-14 07:04 UTC
