### ISSUE TITLE
plugin GRPC not support TLS

### ISSUE THREAD

**Issue by beiwangnull** [apache/skywalking#5349] opened 2020-08-18 12:01 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___

### Bug
- Which version of SkyWalking, OS and JRE?
Skywalking 8.0.2  jdk 8

Caused by: java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
	at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:170)
	at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:150)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.inject(ContextManager.java:123)
	at org.apache.skywalking.apm.plugin.grpc.v1.client.TracingClientCall.start(TracingClientCall.java:84)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:315)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:287)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:196)
	at io.etcd.jetcd.api.KVGrpc$KVFutureStub.range(KVGrpc.java:507)
	at io.etcd.jetcd.KVImpl.lambda$get$3(KVImpl.java:112)
	at io.etcd.jetcd.ClientConnectionManager.lambda$execute$4(ClientConnectionManager.java:306)
	at net.jodah.failsafe.Functions.lambda$toCtxSupplier$15(Functions.java:276)
	at net.jodah.failsafe.Functions.lambda$getPromise$1(Functions.java:81)
	at net.jodah.failsafe.Functions.lambda$null$3(Functions.java:103)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wu-sheng** [comment] 2020-08-18 12:29
What is SkyWalking 8.0.2? We don't have that release.

**Comment by wu-sheng** [comment] 2020-08-18 12:33
@ascrutae I think there are strange codes here.

https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/client/TracingClientCall.java#L73L84

Why the codes do `inject` before the `context#item#put`?

**Comment by wu-sheng** [comment] 2020-08-18 12:46
@beiwangnull Could you try to move https://github.com/apache/skywalking/blob/master/apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/client/TracingClientCall.java#L84 to line 91?

**Comment by wu-sheng** [comment] 2020-08-19 00:51
@devkanro Could you take a look on this? Include my comment about the `injection` not working.

**Comment by devkanro** [comment] 2020-08-19 02:11
@wu-sheng sure assign to me

**Comment by wu-sheng** [comment] 2020-08-19 02:42
Done.

**Comment by beiwangnull** [comment] 2020-08-24 07:52
client and server use TLS
Im use jetcd，connect etcd use by GRPC
![image](https://user-images.githubusercontent.com/3151306/91018194-dc25de80-e621-11ea-9c95-3d10073b0c72.png)

**Comment by devkanro** [comment] 2020-08-25 06:10
After some debug, I found the cause of the bug.  
The Client builder will use `ClientConnectionManager` to build `ManagedChannel` with `SmartNameResolverFactory`.  
When the authority has not been set, SmartNameResolverFactory will be initialized with an empty string authority.

```Java
        channelBuilder.nameResolverFactory(
            forEndpoints(
                Util.supplyIfNull(builder.authority(), () -> ""),
                builder.endpoints(),
                Util.supplyIfNull(builder.uriResolverLoader(),
                    URIResolverLoader::defaultLoader)));
```

\>\> @beiwangnull
you can set the value of authority explicitly to avoid the bug for now.
```Kotlin
            val client = Client.builder()
            .sslContext(context)
            .endpoints("http://server-host:2712")
            .authority("etcd") // Must be a SAN in server cert if <server-host> is not in cert
            .build()
```
Reference: etcd-io/jetcd#55, etcd-io/jetcd#652, grpc/grpc-java#2662

\>\> @wu-sheng 
We need to discuss how we do if we can't get authority from `ManagedChannel`, the name resolver could override the original value of authority.

**Comment by wu-sheng** [comment] 2020-08-26 01:09
@devkanro We just need the remote name or network address. I think we could get that from the stub initialization, right?

**Comment by francis177** [comment] 2020-08-29 09:21
> After some debug, I found the cause of the bug.
> The Jetcd Client builder will use `ClientConnectionManager` to build `ManagedChannel` with `SmartNameResolverFactory`.
> When the authority has not been set, SmartNameResolverFactory will be initialized with an empty string authority.
> 
> ```java
> // io.etcd.jetcd.ClientConnectionManager
>         channelBuilder.nameResolverFactory(
>             forEndpoints(
>                 Util.supplyIfNull(builder.authority(), () -> ""),
>                 builder.endpoints(),
>                 Util.supplyIfNull(builder.uriResolverLoader(),
>                     URIResolverLoader::defaultLoader)));
> ```
> 
> >> @beiwangnull
> you can set the value of authority explicitly to avoid the bug for now.
> 
> ```kotlin
>             val client = Client.builder()
>             .sslContext(context)
>             .endpoints("http://server-host:2712")
>             .authority("etcd") // Must be a SAN in server cert if <server-host> is not in cert
>             .build()
> ```
> 
> Reference: [etcd-io/jetcd#55](https://github.com/etcd-io/jetcd/issues/55), [etcd-io/jetcd#652](https://github.com/etcd-io/jetcd/issues/652), [grpc/grpc-java#2662](https://github.com/grpc/grpc-java/pull/2662)
> 
> >> @wu-sheng
> We need to discuss how we do if we can't get authority from `ManagedChannel`, the name resolver could override the original value of authority.

When using jetcd to connect etcd cluster via mTLS, the server cert will contain more than one domain, aka. etcd-1.com, etcd-2.com, etcd-3.com. Because .authority() accept single string. Separately, etcd-1.com or etcd-2.com or etcd-3.com as authority is all fine. How can I set all these there domains into jetcd client's authority ? Thanks

**Comment by wu-sheng** [comment] 2020-08-29 09:35
@francis177  Could you make your question clear? How to use jetcd is not SkyWalking's concern.

**Comment by devkanro** [comment] 2020-08-30 05:07
Just make your authority same as one domain in your cert, I think.

**Comment by wu-sheng** [comment] 2020-08-30 09:28
@devkanro What is the progress of this issue locating?

**Comment by devkanro** [comment] 2020-08-30 09:51
I am trying to change the plugin to fix this issue...

The intercept point of grpc plugin is the ClientCall now, I'm looking for getting authority from stubs.

**Comment by francis177** [comment] 2020-08-31 03:56
@wu-sheng I'm fixing the same problem with @beiwangnull. Main service access etcd cluster via jetcd, with mTLS enabled. Also using skywalking.

@devkanro before asking, I've verified setting any one of domains in the cert works fine. What if etcd node with the authority domain goes down?

**Comment by devkanro** [comment] 2020-08-31 06:40
@francis177 
I think it will work fine, the value of authority just used for auth. Actually, the client will not connect to it if you don't set it in endpoints.

**Comment by francis177** [comment] 2020-08-31 08:36
@devkanro I set etcd cluster's endpoints []String as client's endpoint, not single etcd node

**Comment by devkanro** [comment] 2020-09-02 06:02
@francis177 
Yes, If you have endpoints with 'etcd1, etcd2, etcd3', and set authority to 'etcd'.
The client will connect to 'etcd1, etcd2, etcd3' not the 'etcd'.

**Comment by devkanro** [comment] 2020-09-02 08:34
> @devkanro We just need the remote name or network address. I think we could get that from the stub initialization, right?

@wu-sheng 
The remote name or network address will not be resolved in stub initialization...
The `ManagedChannelImpl` will call the start method of `NameResolver`, and use the listener to get resolve result.
Maybe hook the stub is not a good choose, we should focus on the `NameResolver` or `SmartNameResolver`. 

Support `NameResolver` for all cases, `SmartNameResolver` for jetcd case. `NameResolver` supporting will be a little complex, `SmartNameResolver` will be easy to support.

For jetcd case, we can detect the grpc client created by jetcd client, and set the default authority to `ExitSpan` if authority not be set.

**Comment by wu-sheng** [comment] 2020-09-05 15:40
I don't have time to read the gRPC source codes as you did/are doing. I could only say, this peer should map to the target instance. No matter as logic name or real network address. Feel free to use any method you need.

**Comment by wu-sheng** [comment] 2021-09-20 09:17
No activity for months.

**Closed by wu-sheng** 2021-09-20 09:17 UTC
Labels: bug, agent, plugin

**Comment by Anthony88888** [comment] 2022-06-25 16:46
Please ask if you can help to confirm that java uses etcd as the registry to report an error
Only the java program registered to etcd will report an error, and the normal use of other unregistered programs is troublesome.
--------------------------------------------------------------------------------------------------
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-06-26 00:27:41.755 ERROR [sleuth_IS_UNDEFINED,,,] 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'checkController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'checkServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'etcdRegistryCenter': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.aibit.PublicApplication.main(PublicApplication.java:20)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'checkServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'etcdRegistryCenter': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
	... 25 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'etcdRegistryCenter': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeanByName(AbstractAutowireCapableBeanFactory.java:479)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:550)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
	... 41 common frames omitted
Caused by: java.lang.IllegalStateException: Exit span doesn't include meaningful peer information.
	at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:170)
	at org.apache.skywalking.apm.agent.core.context.TracingContext.inject(TracingContext.java:150)
	at org.apache.skywalking.apm.agent.core.context.ContextManager.inject(ContextManager.java:123)
	at org.apache.skywalking.apm.plugin.grpc.v1.client.TracingClientCall.start(TracingClientCall.java:84)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332)
	at io.grpc.stub.ClientCalls.asyncStreamingRequestCall(ClientCalls.java:323)
	at io.grpc.stub.ClientCalls.asyncBidiStreamingCall(ClientCalls.java:111)
	at io.etcd.jetcd.api.LeaseGrpc$LeaseStub.leaseKeepAlive(LeaseGrpc.java:313)
	at io.vertx.grpc.stub.ClientCalls.manyToMany(ClientCalls.java:60)
	at io.etcd.jetcd.api.VertxLeaseGrpc$LeaseVertxStub.leaseKeepAlive(VertxLeaseGrpc.java:82)
	at io.etcd.jetcd.impl.LeaseImpl$KeepAlive.doStart(LeaseImpl.java:200)
	at io.etcd.jetcd.common.Service.start(Service.java:30)
	at io.etcd.jetcd.impl.LeaseImpl.keepAlive(LeaseImpl.java:133)
	at com.aibit.manager.etcd.EtcdRegistryCenter.registerInstance$original$Llhz5j79(EtcdRegistryCenter.java:135)
	at com.aibit.manager.etcd.EtcdRegistryCenter.registerInstance$original$Llhz5j79$accessor$wDu1FEMg(EtcdRegistryCenter.java)
	at com.aibit.manager.etcd.EtcdRegistryCenter$auxiliary$o0VwvcGD.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at com.aibit.manager.etcd.EtcdRegistryCenter.registerInstance(EtcdRegistryCenter.java)
	at com.aibit.manager.etcd.EtcdRegistryCenter.init(EtcdRegistryCenter.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 56 common frames omitted

**Comment by Anthony88888** [comment] 2022-06-25 16:47
@wu-sheng   Please help confirm the above questions if you have time, thank you
