### ISSUE TITLE
Fix application cannot start when the dubbo interface with @GetMapping

### ISSUE THREAD

**Issue by martinou** [apache/skywalking#2554] opened 2019-04-29 06:22 UTC
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ .] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of SkyWalking, OS and JRE?
  SkyWalking

- Which company or project?
dubbo 2.7.1

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
 @RestController
@Service
public class OrderController implements OrderService {
    @Autowired
    private OrderService orderService;

    private final static Logger LOGGER = LoggerFactory.getLogger(OrderController.class);

    @GetMapping("/saveorder")
    public String saveOrder() {
        LOGGER.info("saveorder");
        orderService.generateOrder();

        return "ok";
    }

    @Override
    public void generateOrder() {
        orderService.generateOrder();
    }

    @GetMapping(value = "/findOrderById/{orderId}")
    @ResponseBody
    @Override
    public Order findOrderById(@PathVariable("orderId") Long orderId) {
        return orderService.findOrderById(orderId);
    }
}

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by ascrutae** [comment] 2019-05-27 22:31
Cloud you post me that error message?

**Comment by ascrutae** [comment] 2019-06-05 02:33
I close this issue first because I don't reproduce this issue in my environment.  you can reopen it if the issue happened again and you'd better provide the reproduce demo.

**Closed by ascrutae** 2019-06-05 02:33 UTC
Labels: agent, bug, plugin
