### ISSUE TITLE
logstash logback plugin get tid is "TID:N/A"

### ISSUE THREAD

**Issue by HuangDayu** [apache/skywalking#5746] opened 2020-10-28 09:29 UTC
zh_CN：

你好，我的配置如下，控制台的tid是有值，但是logstash 日志的tid值是获取不到的，不知是什么原因，请帮忙看一下，谢谢。

en_US:

Hello, my configuration is as follows. The tid of the console has a value, but the pid value of the logstash log is not available. I don't know the reason. Please help to take a look. Thank you.

- application-dev.yaml

```yaml
logging:
  logstash: '192.168.2.246:4560'
  config: classpath:logback-config.xml
  level:
    com.cloud.*: debug
    org.apache.kafka.clients.*: error
    org.springframework.scheduling.support.*: off
    org.springfromework.*: info
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%tid){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'
  file:
    path: /home/cloud/logs/${spring.application.name}/${spring.application.instance-id}
```

- logback-coonfig.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="10 seconds">

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <springProperty name="spring.application.name" scope="context" source="spring.application.name"/>
    <springProperty name="spring.application.instance-id" scope="context" source="spring.application.instance-id"/>
    <springProperty name="logging.logstash" scope="context" source="logging.logstash"/>
    <springProperty name="logging.pattern.console" scope="context" source="logging.pattern.console"/>
    <springProperty name="logging.file.path" scope="context" source="logging.file.path"/>
    <springProperty name="logging.level" scope="context" source="logging.level"/>


    <property name="LOG_FILE_PATH"
              value="/home/cloud/logs/${spring.application.name}/${spring.application.instance-id}"/>
    <property name="CONSOLE_LOG_PATTERN"
              value="%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%tid){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"/>
    <property name="FILE_LOG_PATTERN"
              value="%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } %tid --- [%t] %-40.40logger{39} : %m%n%wEx"/>

    <!--add converter for %tid -->
    <conversionRule conversionWord="tid"
                    converterClass="org.apache.skywalking.apm.toolkit.log.logback.v1.x.LogbackPatternConverter"/>


    <appender class="ch.qos.logback.core.ConsoleAppender">
        <encoder charset="UTF-8" class="net.logstash.logback.encoder.LogstashEncoder">
            <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
        </encoder>
    </appender>


    <appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>${logging.logstash}</destination>
        <encoder charset="UTF-8" class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <pattern>
                    <pattern>
                        {
                        "level": "%level",
                        "serviceName": "${spring.application.name:-}",
                        "serviceId": "${spring.application.instance-id:-}",
                        "pid": "${PID:-}",
                        "tid": "%tid",
                        "thread": "%thread",
                        "class": "%logger{1.}:%L",
                        "message": "%message",
                        "stackTrace": "%exception{10}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>

    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <Pattern>${CONSOLE_LOG_PATTERN}</Pattern>
            </layout>
        </encoder>
    </appender>

    <appender name="output" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <File>${LOG_FILE_PATH}/spring.log</File>

        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <FileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}.%i.log.gz</FileNamePattern>
            <MaxHistory>30</MaxHistory>
            <maxFileSize>10MB</maxFileSize>
        </rollingPolicy>

        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <Pattern>${CONSOLE_LOG_PATTERN}</Pattern>
            </layout>
        </encoder>

    </appender>

    <root level="INFO">
        <appender-ref ref="logstash"/>

        <appender-ref ref="console"/>
    </root>

    <springProfile name="test | dev | prod">
        <logger name="com.cloud.iot.*" level="debug"/>
        <logger name="org.apache.kafka.clients.*" level="error"/>
        <logger name="org.springframework.scheduling.support.*" level="off" addtivity="false">
            <appender-ref ref="console"/>
        </logger>
        <logger name="org.springfromework.*" level="info"/>
    </springProfile>


</configuration>
```

- console logger

![image](https://user-images.githubusercontent.com/23421574/97416751-cf837680-1941-11eb-8c9b-6b29525c70da.png)

- logstash logger

![image](https://user-images.githubusercontent.com/23421574/97417009-25581e80-1942-11eb-8286-5744998a35e1.png)

- skywalking logger

![image](https://user-images.githubusercontent.com/23421574/97417260-694b2380-1942-11eb-9e23-a793e5141924.png)

**Comment by kezhenxu94** [comment] 2020-10-28 09:36
Duplicate of #3713 

Are you using 8.1.0- or older version?

**Comment by kezhenxu94** [comment] 2020-10-28 09:37
Are you using 8.1.0- or older version?

**Closed by kezhenxu94** 2020-10-28 09:36 UTC

**Comment by HuangDayu** [comment] 2020-10-28 11:10
解决了

```xml
    <appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>${logging.logstash}</destination>
        <encoder charset="UTF-8" class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
                <timestamp>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <pattern>
                    <pattern>
                        {
                        "level": "%level",
                        "serviceName": "${spring.application.name:-}",
                        "serviceId": "${spring.application.instance-id:-}",
                        "pid": "${PID:-}",
                        "tid": "%tid",
                        "thread": "%thread",
                        "class": "%logger{1.}:%L",
                        "message": "%message",
                        "stackTrace": "%exception{10}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>

    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <discardingThreshold>0</discardingThreshold>
        <queueSize>256</queueSize>
        <appender-ref ref="logstash"/>
    </appender>
```

**Comment by wuxingye** [comment] 2020-10-28 12:07
my logback-spring.xml file

    <appender name="STASH" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>127.0.0.1:4560</destination>
        <reconnectionDelay>1 second</reconnectionDelay>
        <encoder charset="UTF-8" class="net.logstash.logback.encoder.LogstashEncoder">
            <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider">
            </provider>
            <customFields>{"app":"server"}</customFields>
        </encoder>
    </appender>

**Comment by Johor03** [comment] 2021-02-15 07:37
> 解决了
> 
> ```
>     <appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
>         <destination>${logging.logstash}</destination>
>         <encoder charset="UTF-8" class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
>             <providers>
>                 <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
>                 <timestamp>
>                     <timeZone>UTC</timeZone>
>                 </timestamp>
>                 <pattern>
>                     <pattern>
>                         {
>                         "level": "%level",
>                         "serviceName": "${spring.application.name:-}",
>                         "serviceId": "${spring.application.instance-id:-}",
>                         "pid": "${PID:-}",
>                         "tid": "%tid",
>                         "thread": "%thread",
>                         "class": "%logger{1.}:%L",
>                         "message": "%message",
>                         "stackTrace": "%exception{10}"
>                         }
>                     </pattern>
>                 </pattern>
>             </providers>
>         </encoder>
>     </appender>
> 
>     <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
>         <discardingThreshold>0</discardingThreshold>
>         <queueSize>256</queueSize>
>         <appender-ref ref="logstash"/>
>     </appender>
> ```

你好，你这个是怎么解决的，我用的配置在logstash 还是获取不到TID

**Comment by Johor03** [comment] 2021-02-15 07:42
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="30 seconds">

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <springProperty name="spring.application.name" scope="context" source="spring.application.name"/>
    <springProperty name="spring.application.instance-id" scope="context" source="spring.application.instance-id"/>
    <springProperty name="logging.logstash" scope="context" source="logging.logstash"/>
    <springProperty name="logging.pattern.console" scope="context" source="logging.pattern.console"/>


    <property name="CONSOLE_LOG_PATTERN"
              value="%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%tid){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"/>
    <property name="FILE_LOG_PATTERN"
              value="%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } %tid --- [%t] %-40.40logger{39} : %m%n%wEx"/>

    <!--add converter for %tid -->
    <conversionRule conversionWord="tid" converterClass="org.apache.skywalking.apm.toolkit.log.logback.v1.x.LogbackPatternConverter"/>


    <appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>10.0.5.218:9600</destination>
        <encoder charset="UTF-8" class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
                <timestamp>
                    <timeZone>UTC</timeZone>
                </timestamp>
                <pattern>
                    <pattern>
                        {
                        "level": "%level",
                        "serviceName": "${spring.application.name:-}",
                        "pid": "${PID:-}",
                        "tid": "%tid",
                        "thread": "%thread",
                        "class": "%logger{1.}",
                        "message": "%message",
                        "stackTrace": "%exception{10}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
    </appender>

    <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <discardingThreshold>0</discardingThreshold>
        <queueSize>512</queueSize>
        <appender-ref ref="logstash"/>
    </appender>


    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
                <Pattern>${CONSOLE_LOG_PATTERN}</Pattern>
            </layout>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="logstash"/>
        <appender-ref ref="console"/>
    </root>
</configuration>
```

maven 依赖
```
<dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
            <version>8.4.0</version>
        </dependency>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>6.6</version>
        </dependency>
```

**Comment by Johor03** [comment] 2021-02-15 07:43
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <configuration scan="true" scanPeriod="30 seconds">
> 
>     <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
> 
>     <springProperty name="spring.application.name" scope="context" source="spring.application.name"/>
>     <springProperty name="spring.application.instance-id" scope="context" source="spring.application.instance-id"/>
>     <springProperty name="logging.logstash" scope="context" source="logging.logstash"/>
>     <springProperty name="logging.pattern.console" scope="context" source="logging.pattern.console"/>
> 
> 
>     <property name="CONSOLE_LOG_PATTERN"
>               value="%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%tid){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"/>
>     <property name="FILE_LOG_PATTERN"
>               value="%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } %tid --- [%t] %-40.40logger{39} : %m%n%wEx"/>
> 
>     
>     <conversionRule conversionWord="tid" converterClass="org.apache.skywalking.apm.toolkit.log.logback.v1.x.LogbackPatternConverter"/>
> 
> 
>     <appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
>         <destination>10.0.5.218:9600</destination>
>         <encoder charset="UTF-8" class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
>             <providers>
>                 <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
>                 <timestamp>
>                     <timeZone>UTC</timeZone>
>                 </timestamp>
>                 <pattern>
>                     <pattern>
>                         {
>                         "level": "%level",
>                         "serviceName": "${spring.application.name:-}",
>                         "pid": "${PID:-}",
>                         "tid": "%tid",
>                         "thread": "%thread",
>                         "class": "%logger{1.}",
>                         "message": "%message",
>                         "stackTrace": "%exception{10}"
>                         }
>                     </pattern>
>                 </pattern>
>             </providers>
>         </encoder>
>     </appender>
> 
>     <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
>         <discardingThreshold>0</discardingThreshold>
>         <queueSize>512</queueSize>
>         <appender-ref ref="logstash"/>
>     </appender>
> 
> 
>     <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
>         <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
>             <layout class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.TraceIdPatternLogbackLayout">
>                 <Pattern>${CONSOLE_LOG_PATTERN}</Pattern>
>             </layout>
>         </encoder>
>     </appender>
> 
>     <root level="INFO">
>         <appender-ref ref="logstash"/>
>         <appender-ref ref="console"/>
>     </root>
> </configuration>
> ```
> 
> maven 依赖
> 
> ```
> <dependency>
>             <groupId>org.apache.skywalking</groupId>
>             <artifactId>apm-toolkit-logback-1.x</artifactId>
>             <version>8.4.0</version>
>         </dependency>
>         <dependency>
>             <groupId>net.logstash.logback</groupId>
>             <artifactId>logstash-logback-encoder</artifactId>
>             <version>6.6</version>
>         </dependency>
> ```

@HuangDayu 能帮忙看下吗

**Comment by qlanto224** [comment] 2024-04-17 11:37
> 解决了
> 
> ```
>     <appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
>         <destination>${logging.logstash}</destination>
>         <encoder charset="UTF-8" class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
>             <providers>
>                 <provider class="org.apache.skywalking.apm.toolkit.log.logback.v1.x.logstash.TraceIdJsonProvider"/>
>                 <timestamp>
>                     <timeZone>UTC</timeZone>
>                 </timestamp>
>                 <pattern>
>                     <pattern>
>                         {
>                         "level": "%level",
>                         "serviceName": "${spring.application.name:-}",
>                         "serviceId": "${spring.application.instance-id:-}",
>                         "pid": "${PID:-}",
>                         "tid": "%tid",
>                         "thread": "%thread",
>                         "class": "%logger{1.}:%L",
>                         "message": "%message",
>                         "stackTrace": "%exception{10}"
>                         }
>                     </pattern>
>                 </pattern>
>             </providers>
>         </encoder>
>     </appender>
> 
>     <appender name="ASYNC" class="ch.qos.logback.classic.AsyncAppender">
>         <discardingThreshold>0</discardingThreshold>
>         <queueSize>256</queueSize>
>         <appender-ref ref="logstash"/>
>     </appender>
> ```

大佬,等于说要使用LoggingEventCompositeJsonEncoder,必须要用异步发送?
